# Default lucky-wheel prizes (editable later in admin).
# label_line1/2 are short wheel labels; title_* are full names.

DEFAULT_LUCKY_WHEEL_PRIZES = [
    {
        "label_line1_az": "Pulsuz",
        "label_line2_az": "Sınaq Dərsi",
        "label_line1_en": "Free",
        "label_line2_en": "Trial Lesson",
        "label_line1_ru": "Бесплатный",
        "label_line2_ru": "пробный урок",
        "title_az": "Pulsuz Sınaq Dərsi",
        "title_en": "Free Trial Lesson",
        "title_ru": "Бесплатный пробный урок",
        "weight": 12,
        "is_win": True,
        "is_respin": False,
        "order": 10,
    },
    {
        "label_line1_az": "Pulsuz",
        "label_line2_az": "Səviyyə Testi",
        "label_line1_en": "Free",
        "label_line2_en": "Level Test",
        "label_line1_ru": "Бесплатный",
        "label_line2_ru": "тест уровня",
        "title_az": "Pulsuz Səviyyə Testi",
        "title_en": "Free Level Test",
        "title_ru": "Бесплатный тест на определение уровня",
        "weight": 12,
        "is_win": True,
        "is_respin": False,
        "order": 20,
    },
    {
        "label_line1_az": "Conversation Club",
        "label_line2_az": "1 Həftə HƏDİYYƏ",
        "label_line1_en": "Conversation Club",
        "label_line2_en": "1 Week FREE",
        "label_line1_ru": "Conversation Club",
        "label_line2_ru": "1 неделя БЕСПЛАТНО",
        "title_az": "Conversation Club — 1 Həftə HƏDİYYƏ",
        "title_en": "Conversation Club — 1 Week FREE",
        "title_ru": "Conversation Club — 1 неделя БЕСПЛАТНО",
        "weight": 8,
        "is_win": True,
        "is_respin": False,
        "order": 30,
    },
    {
        "label_line1_az": "Dərs Materialları",
        "label_line2_az": "HƏDİYYƏ",
        "label_line1_en": "Course Materials",
        "label_line2_en": "FREE",
        "label_line1_ru": "Учебные материалы",
        "label_line2_ru": "БЕСПЛАТНО",
        "title_az": "Dərs Materialları — HƏDİYYƏ",
        "title_en": "Course Materials — FREE",
        "title_ru": "Учебные материалы — БЕСПЛАТНО",
        "weight": 10,
        "is_win": True,
        "is_respin": False,
        "order": 40,
    },
    {
        "label_line1_az": "5%",
        "label_line2_az": "ENDİRİM",
        "label_line1_en": "5%",
        "label_line2_en": "DISCOUNT",
        "label_line1_ru": "СКИДКА",
        "label_line2_ru": "5%",
        "title_az": "5% ENDİRİM",
        "title_en": "5% DISCOUNT",
        "title_ru": "СКИДКА 5%",
        "weight": 14,
        "is_win": True,
        "is_respin": False,
        "order": 50,
    },
    {
        "label_line1_az": "10%",
        "label_line2_az": "ENDİRİM",
        "label_line1_en": "10%",
        "label_line2_en": "DISCOUNT",
        "label_line1_ru": "СКИДКА",
        "label_line2_ru": "10%",
        "title_az": "10% ENDİRİM",
        "title_en": "10% DISCOUNT",
        "title_ru": "СКИДКА 10%",
        "weight": 10,
        "is_win": True,
        "is_respin": False,
        "order": 60,
    },
    {
        "label_line1_az": "10 AZN",
        "label_line2_az": "HƏDİYYƏ KUPONU",
        "label_line1_en": "10 AZN",
        "label_line2_en": "GIFT VOUCHER",
        "label_line1_ru": "КУПОН",
        "label_line2_ru": "10 AZN",
        "title_az": "10 AZN HƏDİYYƏ KUPONU",
        "title_en": "10 AZN GIFT VOUCHER",
        "title_ru": "ПОДАРОЧНЫЙ КУПОН НА 10 AZN",
        "weight": 8,
        "is_win": True,
        "is_respin": False,
        "order": 70,
    },
    {
        "label_line1_az": "20 AZN",
        "label_line2_az": "HƏDİYYƏ KUPONU",
        "label_line1_en": "20 AZN",
        "label_line2_en": "GIFT VOUCHER",
        "label_line1_ru": "КУПОН",
        "label_line2_ru": "20 AZN",
        "title_az": "20 AZN HƏDİYYƏ KUPONU",
        "title_en": "20 AZN GIFT VOUCHER",
        "title_ru": "ПОДАРОЧНЫЙ КУПОН НА 20 AZN",
        "weight": 5,
        "is_win": True,
        "is_respin": False,
        "order": 80,
    },
    {
        "label_line1_az": "Paper Mock",
        "label_line2_az": "HƏDİYYƏ",
        "label_line1_en": "Paper Mock",
        "label_line2_en": "FREE",
        "label_line1_ru": "Paper Mock",
        "label_line2_ru": "БЕСПЛАТНО",
        "title_az": "Paper-Based Mock Test — HƏDİYYƏ",
        "title_en": "Paper-Based Mock Test — FREE",
        "title_ru": "Paper-Based Mock Test — БЕСПЛАТНО",
        "weight": 7,
        "is_win": True,
        "is_respin": False,
        "order": 90,
    },
    {
        "label_line1_az": "Computer Mock",
        "label_line2_az": "HƏDİYYƏ",
        "label_line1_en": "Computer Mock",
        "label_line2_en": "FREE",
        "label_line1_ru": "Computer Mock",
        "label_line2_ru": "БЕСПЛАТНО",
        "title_az": "Computer-Based Mock Test — HƏDİYYƏ",
        "title_en": "Computer-Based Mock Test — FREE",
        "title_ru": "Computer-Based Mock Test — БЕСПЛАТНО",
        "weight": 7,
        "is_win": True,
        "is_respin": False,
        "order": 100,
    },
    {
        "label_line1_az": "SÜRPRİZ",
        "label_line2_az": "HƏDİYYƏ",
        "label_line1_en": "SURPRISE",
        "label_line2_en": "GIFT",
        "label_line1_ru": "СЮРПРИЗ",
        "label_line2_ru": "ПОДАРОК",
        "title_az": "SÜRPRİZ HƏDİYYƏ",
        "title_en": "SURPRISE GIFT",
        "title_ru": "СЮРПРИЗ-ПОДАРОК",
        "weight": 4,
        "is_win": True,
        "is_respin": False,
        "order": 110,
    },
    {
        "label_line1_az": "BİR DAHA",
        "label_line2_az": "ÇEVİR",
        "label_line1_en": "SPIN",
        "label_line2_en": "AGAIN",
        "label_line1_ru": "КРУТИ",
        "label_line2_ru": "ЕЩЁ РАЗ",
        "title_az": "BİR DAHA ÇEVİR",
        "title_en": "SPIN AGAIN",
        "title_ru": "КРУТИ ЕЩЁ РАЗ",
        "weight": 8,
        "is_win": False,
        "is_respin": True,
        "order": 120,
    },
    {
        "label_line1_az": "ŞANSINI",
        "label_line2_az": "YENİDƏN SINA",
        "label_line1_en": "TRY YOUR",
        "label_line2_en": "LUCK AGAIN",
        "label_line1_ru": "ПОПРОБУЙ",
        "label_line2_ru": "УДАЧУ ЕЩЁ РАЗ",
        "title_az": "ŞANSINI YENİDƏN SINA",
        "title_en": "TRY YOUR LUCK AGAIN",
        "title_ru": "ПОПРОБУЙ УДАЧУ ЕЩЁ РАЗ",
        "weight": 8,
        "is_win": False,
        "is_respin": True,
        "order": 130,
    },
    {
        "label_line1_az": "VIP",
        "label_line2_az": "HƏDİYYƏ",
        "label_line1_en": "VIP",
        "label_line2_en": "GIFT",
        "label_line1_ru": "VIP",
        "label_line2_ru": "ПОДАРОК",
        "title_az": "VIP HƏDİYYƏ",
        "title_en": "VIP GIFT",
        "title_ru": "VIP-ПОДАРОК",
        "weight": 3,
        "is_win": True,
        "is_respin": False,
        "order": 140,
    },
    {
        "label_line1_az": "PULSUZ",
        "label_line2_az": "E-BOOK",
        "label_line1_en": "FREE",
        "label_line2_en": "E-BOOK",
        "label_line1_ru": "БЕСПЛАТНЫЙ",
        "label_line2_ru": "E-BOOK",
        "title_az": "PULSUZ E-BOOK",
        "title_en": "FREE E-BOOK",
        "title_ru": "БЕСПЛАТНЫЙ E-BOOK",
        "weight": 9,
        "is_win": True,
        "is_respin": False,
        "order": 150,
    },
    {
        "label_line1_az": "Listening",
        "label_line2_az": "HƏDİYYƏ",
        "label_line1_en": "Listening",
        "label_line2_en": "FREE",
        "label_line1_ru": "Listening",
        "label_line2_ru": "БЕСПЛАТНО",
        "title_az": "Listening Materialları — HƏDİYYƏ",
        "title_en": "Listening Materials — FREE",
        "title_ru": "Материалы для Listening — БЕСПЛАТНО",
        "weight": 9,
        "is_win": True,
        "is_respin": False,
        "order": 160,
    },
    {
        "label_line1_az": "Pulsuz",
        "label_line2_az": "Writing Yoxlanışı",
        "label_line1_en": "Free",
        "label_line2_en": "Writing Assessment",
        "label_line1_ru": "Бесплатная",
        "label_line2_ru": "проверка Writing",
        "title_az": "Pulsuz Writing Yoxlanışı",
        "title_en": "Free Writing Assessment",
        "title_ru": "Бесплатная проверка Writing",
        "weight": 8,
        "is_win": True,
        "is_respin": False,
        "order": 170,
    },
    {
        "label_line1_az": "Speaking",
        "label_line2_az": "HƏDİYYƏ",
        "label_line1_en": "Speaking",
        "label_line2_en": "FREE",
        "label_line1_ru": "Speaking",
        "label_line2_ru": "БЕСПЛАТНО",
        "title_az": "Speaking Assessment — HƏDİYYƏ",
        "title_en": "Speaking Assessment — FREE",
        "title_ru": "Speaking Assessment — БЕСПЛАТНО",
        "weight": 8,
        "is_win": True,
        "is_respin": False,
        "order": 180,
    },
]
