# Default lucky-wheel prizes (editable later in admin).
# label_line1/2 are short wheel labels; title_* are full names.

DEFAULT_LUCKY_WHEEL_PRIZES = [
    {
        "label_line1_az": "Pulsuz",
        "label_line2_az": "Sınaq Dərsi",
        "label_line1_en": "Free",
        "label_line2_en": "Trial Lesson",
        "label_line1_ru": "Бесплатный",
        "label_line2_ru": "пробный урок",
        "title_az": "Pulsuz Sınaq Dərsi",
        "title_en": "Free Trial Lesson",
        "title_ru": "Бесплатный пробный урок",
        "weight": 12,
        "is_win": True,
        "is_respin": False,
        "order": 10,
    },
    {
        "label_line1_az": "Pulsuz",
        "label_line2_az": "Səviyyə Testi",
        "label_line1_en": "Free",
        "label_line2_en": "Level Test",
        "label_line1_ru": "Бесплатный",
        "label_line2_ru": "тест уровня",
        "title_az": "Pulsuz Səviyyə Testi",
        "title_en": "Free Level Test",
        "title_ru": "Бесплатный тест на определение уровня",
        "weight": 12,
        "is_win": True,
        "is_respin": False,
        "order": 20,
    },
    {
        "label_line1_az": "Conversation Club",
        "label_line2_az": "1 Həftə HƏDİYYƏ",
        "label_line1_en": "Conversation Club",
        "label_line2_en": "1 Week FREE",
        "label_line1_ru": "Conversation Club",
        "label_line2_ru": "1 неделя БЕСПЛАТНО",
        "title_az": "Conversation Club — 1 Həftə HƏDİYYƏ",
        "title_en": "Conversation Club — 1 Week FREE",
        "title_ru": "Conversation Club — 1 неделя БЕСПЛАТНО",
        "weight": 8,
        "is_win": True,
        "is_respin": False,
        "order": 30,
    },
    {
        "label_line1_az": "5%",
        "label_line2_az": "ENDİRİM",
        "label_line1_en": "5%",
        "label_line2_en": "DISCOUNT",
        "label_line1_ru": "СКИДКА",
        "label_line2_ru": "5%",
        "title_az": "5% ENDİRİM",
        "title_en": "5% DISCOUNT",
        "title_ru": "СКИДКА 5%",
        "weight": 14,
        "is_win": True,
        "is_respin": False,
        "order": 40,
    },
    {
        "label_line1_az": "10%",
        "label_line2_az": "ENDİRİM",
        "label_line1_en": "10%",
        "label_line2_en": "DISCOUNT",
        "label_line1_ru": "СКИДКА",
        "label_line2_ru": "10%",
        "title_az": "10% ENDİRİM",
        "title_en": "10% DISCOUNT",
        "title_ru": "СКИДКА 10%",
        "weight": 10,
        "is_win": True,
        "is_respin": False,
        "order": 50,
    },
    {
        "label_line1_az": "Mock Test",
        "label_line2_az": "HƏDİYYƏ",
        "label_line1_en": "Mock Test",
        "label_line2_en": "FREE",
        "label_line1_ru": "Mock Test",
        "label_line2_ru": "БЕСПЛАТНО",
        "title_az": "Mock Test — HƏDİYYƏ",
        "title_en": "Mock Test — FREE",
        "title_ru": "Mock Test — БЕСПЛАТНО",
        "weight": 10,
        "is_win": True,
        "is_respin": False,
        "order": 60,
    },
    {
        "label_line1_az": "SÜRPRİZ",
        "label_line2_az": "HƏDİYYƏ",
        "label_line1_en": "SURPRISE",
        "label_line2_en": "GIFT",
        "label_line1_ru": "СЮРПРИЗ",
        "label_line2_ru": "ПОДАРОК",
        "title_az": "SÜRPRİZ HƏDİYYƏ",
        "title_en": "SURPRISE GIFT",
        "title_ru": "СЮРПРИЗ-ПОДАРОК",
        "weight": 4,
        "is_win": True,
        "is_respin": False,
        "order": 70,
    },
    {
        "label_line1_az": "BİR DAHA",
        "label_line2_az": "ÇEVİR",
        "label_line1_en": "SPIN",
        "label_line2_en": "AGAIN",
        "label_line1_ru": "КРУТИ",
        "label_line2_ru": "ЕЩЁ РАЗ",
        "title_az": "BİR DAHA ÇEVİR",
        "title_en": "SPIN AGAIN",
        "title_ru": "КРУТИ ЕЩЁ РАЗ",
        "weight": 8,
        "is_win": False,
        "is_respin": True,
        "order": 80,
    },
    {
        "label_line1_az": "ŞANSINI",
        "label_line2_az": "YENİDƏN SINA",
        "label_line1_en": "TRY YOUR",
        "label_line2_en": "LUCK AGAIN",
        "label_line1_ru": "ПОПРОБУЙ",
        "label_line2_ru": "УДАЧУ ЕЩЁ РАЗ",
        "title_az": "ŞANSINI YENİDƏN SINA",
        "title_en": "TRY YOUR LUCK AGAIN",
        "title_ru": "ПОПРОБУЙ УДАЧУ ЕЩЁ РАЗ",
        "weight": 8,
        "is_win": False,
        "is_respin": True,
        "order": 90,
    },
    {
        "label_line1_az": "Pulsuz",
        "label_line2_az": "quizlər",
        "label_line1_en": "Free",
        "label_line2_en": "quizzes",
        "label_line1_ru": "Бесплатные",
        "label_line2_ru": "квизы",
        "title_az": "Pulsuz quizlər",
        "title_en": "Free quizzes",
        "title_ru": "Бесплатные квизы",
        "weight": 9,
        "is_win": True,
        "is_respin": False,
        "order": 100,
    },
    {
        "label_line1_az": "Listening",
        "label_line2_az": "HƏDİYYƏ",
        "label_line1_en": "Listening",
        "label_line2_en": "FREE",
        "label_line1_ru": "Listening",
        "label_line2_ru": "БЕСПЛАТНО",
        "title_az": "Listening Materialları — HƏDİYYƏ",
        "title_en": "Listening Materials — FREE",
        "title_ru": "Материалы для Listening — БЕСПЛАТНО",
        "weight": 9,
        "is_win": True,
        "is_respin": False,
        "order": 110,
    },
    {
        "label_line1_az": "Pulsuz",
        "label_line2_az": "Writing Yoxlanışı",
        "label_line1_en": "Free",
        "label_line2_en": "Writing Assessment",
        "label_line1_ru": "Бесплатная",
        "label_line2_ru": "проверка Writing",
        "title_az": "Pulsuz Writing Yoxlanışı",
        "title_en": "Free Writing Assessment",
        "title_ru": "Бесплатная проверка Writing",
        "weight": 8,
        "is_win": True,
        "is_respin": False,
        "order": 120,
    },
    {
        "label_line1_az": "Speaking",
        "label_line2_az": "HƏDİYYƏ",
        "label_line1_en": "Speaking",
        "label_line2_en": "FREE",
        "label_line1_ru": "Speaking",
        "label_line2_ru": "БЕСПЛАТНО",
        "title_az": "Speaking Assessment — HƏDİYYƏ",
        "title_en": "Speaking Assessment — FREE",
        "title_ru": "Speaking Assessment — БЕСПЛАТНО",
        "weight": 8,
        "is_win": True,
        "is_respin": False,
        "order": 130,
    },
]
