from django.urls import path
from django.views.generic import RedirectView

from projects.views.views_v1 import (
    HomePageView,
    CoursesPageView,
    CourseDetailPageView,
    MockTestsPageView,
    MockTestDetailPageView,
    AboutPageView,
    ServicesPageView,
    AbroadPageView,
    AbroadUniversityDetailPageView,
    AbroadDetailLegacyPkRedirectView,
    AbroadDetailPageView,
    ContactPageView,
    TeamPageView,
    TeamDetailLegacyPkRedirectView,
    TeamDetailPageView,
    BlogPageView,
    BlogPostsPartialView,
    BlogTagPageView,
    BlogDetailLegacyPkRedirectView,
    BlogDetailPageView,
    PrivacyPolicyPageView,
)
from projects.views.test_views import TestListPageView, TestTakePageView
from projects.views.mock_results_views import MockResultsPageView, MockResultsTop5View
from projects.views.conversation_topics_views import (
    EnglishConversationTopicsListView,
    EnglishConversationTopicDetailView,
    LegacyLearnEnglishConversationTopicRedirectView,
    LegacyTopicTwoRedirectView,
)


app_name = 'projects'

urlpatterns = [
    path(
        '', 
        HomePageView.as_view(),
        name='home-page'
    ),
    path(
        'courses/',
        CoursesPageView.as_view(),
        name='courses-page'
    ),
    path(
        'courses/<slug:slug>/',
        CourseDetailPageView.as_view(),
        name='course-detail'
    ),
    path(
        'mock-tests/',
        MockTestsPageView.as_view(),
        name='mock-tests-page',
    ),
    path(
        'mock-tests/<slug:slug>/',
        MockTestDetailPageView.as_view(),
        name='mock-test-detail',
    ),
    path(
        'about/', 
        AboutPageView.as_view(), 
        name='about-page'
    ),
    path(
        'services/',
        ServicesPageView.as_view(),
        name='services-page'
    ),
    path(
        'abroad/',
        AbroadPageView.as_view(),
        name='abroad-page'
    ),
    path(
        'abroad/<int:pk>/',
        AbroadDetailLegacyPkRedirectView.as_view(),
    ),
    path(
        'abroad/universities/<slug:slug>/',
        AbroadUniversityDetailPageView.as_view(),
        name='abroad-university-detail',
    ),
    path(
        'abroad/<slug:slug>/',
        AbroadDetailPageView.as_view(),
        name='abroad-detail'
    ),
    path(
        'contact/', 
        ContactPageView.as_view(), 
        name='contact-page'
    ),
    path(
        'privacy-policy/',
        PrivacyPolicyPageView.as_view(),
        name='privacy-policy',
    ),
    path(
        'team/',
        TeamPageView.as_view(),
        name='team-page',
    ),
    path(
        'team/<int:pk>/',
        TeamDetailLegacyPkRedirectView.as_view(),
    ),
    path(
        'team/<slug:slug>/',
        TeamDetailPageView.as_view(),
        name='team-detail',
    ),
    path(
        'reviews/',
        RedirectView.as_view(pattern_name='home-page', permanent=True),
    ),
    path(
        'blog/posts/',
        BlogPostsPartialView.as_view(),
        name='blog-posts-partial',
    ),
    path(
        'blog/',
        BlogPageView.as_view(),
        name='blog-page',
    ),
    path(
        'blog/tag/<slug:slug>/',
        BlogTagPageView.as_view(),
        name='blog-tag-page',
    ),
    path(
        'blog/<int:pk>/',
        BlogDetailLegacyPkRedirectView.as_view(),
    ),
    path(
        'blog/<slug:slug>/',
        BlogDetailPageView.as_view(),
        name='blog-detail',
    ),
    path(
        'tests/',
        TestListPageView.as_view(),
        name='tests-page',
    ),
    path(
        'tests/<int:test_id>/',
        TestTakePageView.as_view(),
        name='test-take',
    ),
    path(
        'results/',
        MockResultsPageView.as_view(),
        name='results-page',
    ),
    path(
        'results/top5/',
        MockResultsTop5View.as_view(),
        name='results-top5',
    ),
    path(
        'topics/',
        EnglishConversationTopicsListView.as_view(),
        name='english-conversation-topics',
    ),
    path(
        'topics/two/',
        LegacyTopicTwoRedirectView.as_view(),
        name='english-conversation-topic-two-legacy',
    ),
    path(
        'topics/<slug:slug>/',
        EnglishConversationTopicDetailView.as_view(),
        name='english-conversation-topic-detail',
    ),
    path(
        'learn/english-conversation-topics/two/',
        LegacyTopicTwoRedirectView.as_view(),
    ),
    path(
        'learn/english-conversation-topics/<slug:slug>/',
        LegacyLearnEnglishConversationTopicRedirectView.as_view(),
    ),
    path(
        'learn/english-conversation-topics/',
        RedirectView.as_view(
            pattern_name='english-conversation-topics',
            permanent=True,
        ),
    ),
]   
