from django.urls import path

from portals.views.auth_views import PortalLoginView, PortalLogoutView
from portals.views.profile_views import PortalProfileView
from portals.views.teacher_manage_views import (
    TeacherAttendanceCreateView,
    TeacherLessonCreateView,
    TeacherLessonEditView,
    TeacherScheduleCreateView,
    TeacherScheduleDeleteView,
    TeacherScheduleEditView,
    TeacherScheduleSlotCreateView,
    TeacherSessionAttendanceView,
    TeacherTextbookCreateView,
    TeacherTextbookEditView,
    TeacherWeeklyScoresView,
)
from portals.views.notification_views import (
    NotificationDeleteView,
    NotificationMarkAllReadView,
    NotificationMarkReadView,
    ParentNotificationsView,
    ParentScoreDetailView,
    StudentNotificationsView,
    StudentScoreDetailView,
    TeacherNotificationsView,
    TeacherScoreDetailView,
)
from portals.views.quiz_assignment_views import (
    TeacherMockAccessToggleView,
    TeacherQuizAssignmentToggleView,
)
from portals.views.quiz_views import (
    StudentManualQuizSubmitView,
    StudentManualQuizTakeView,
    StudentQuizCancelView,
    StudentReadingQuizSubmitView,
    StudentReadingQuizTakeView,
    StudentSpeakingQuizSubmitView,
    StudentSpeakingQuizTakeView,
    StudentQuizStartView,
    StudentQuizSubmitView,
    StudentQuizTakeView,
    TeacherQuizResultReviewView,
    TeacherQuizResultsView,
)
from portals.views.ielts_mock_views import (
    StudentIeltsMockCompleteView,
    StudentIeltsMockLandingView,
    StudentIeltsMockStartView,
    ParentIeltsMockDetailView,
    TeacherIeltsMockDetailView,
)
from portals.views.views_v1 import (
    ParentAttendanceView,
    ParentDashboardView,
    ParentLessonDetailView,
    ParentLessonsView,
    ParentScheduleView,
    ParentScoresView,
    PortalDashboardView,
    StudentDashboardView,
    StudentLessonDetailView,
    StudentLessonsView,
    StudentQuizCategoryDetailView,
    StudentQuizzesView,
    StudentScheduleView,
    StudentScoresView,
    StudentQuizHistoryLoadView,
    TeacherAttendanceListView,
    TeacherStudentAttendanceDetailView,
    TeacherStudentProfileView,
    TeacherDashboardView,
    TeacherGroupDetailView,
    TeacherGroupsListView,
    TeacherLessonDetailView,
    TeacherLessonsListView,
    TeacherQuizCategoryDetailView,
    TeacherQuizDetailView,
    TeacherQuizzesListView,
    TeacherScheduleView,
    TeacherScoresListView,
    ClassroomsListView,
    ClassroomDetailView,
)

app_name = 'portals'

urlpatterns = [
    path('login/', PortalLoginView.as_view(), name='login'),
    path('logout/', PortalLogoutView.as_view(), name='logout'),
    path('profile/', PortalProfileView.as_view(), name='profile'),
    path('notifications/<int:pk>/read/', NotificationMarkReadView.as_view(), name='notification-mark-read'),
    path('notifications/<int:pk>/delete/', NotificationDeleteView.as_view(), name='notification-delete'),
    path('notifications/mark-all-read/', NotificationMarkAllReadView.as_view(), name='notification-mark-all-read'),
    path('', PortalDashboardView.as_view(), name='dashboard'),

    path('teacher/', TeacherDashboardView.as_view(), name='teacher-dashboard'),
    path('teacher/groups/', TeacherGroupsListView.as_view(), name='teacher-groups'),
    path('teacher/groups/<int:pk>/', TeacherGroupDetailView.as_view(), name='teacher-group-detail'),
    path('teacher/groups/<int:group_pk>/schedule/new/', TeacherScheduleCreateView.as_view(), name='teacher-schedule-create'),
    path('teacher/schedule/new/', TeacherScheduleSlotCreateView.as_view(), name='teacher-schedule-slot-create'),
    path('teacher/schedule/<int:schedule_pk>/edit/', TeacherScheduleEditView.as_view(), name='teacher-schedule-edit'),
    path('teacher/schedule/<int:schedule_pk>/delete/', TeacherScheduleDeleteView.as_view(), name='teacher-schedule-delete'),
    path('teacher/lessons/', TeacherLessonsListView.as_view(), name='teacher-lessons'),
    path('teacher/lessons/new/', TeacherLessonCreateView.as_view(), name='teacher-lesson-create'),
    path('teacher/lessons/<int:pk>/', TeacherLessonDetailView.as_view(), name='teacher-lesson-detail'),
    path('teacher/lessons/<int:pk>/edit/', TeacherLessonEditView.as_view(), name='teacher-lesson-edit'),
    path('teacher/classrooms/new/', TeacherTextbookCreateView.as_view(), name='teacher-classroom-create'),
    path('teacher/classrooms/<int:pk>/edit/', TeacherTextbookEditView.as_view(), name='teacher-classroom-edit'),
    path('teacher/schedule/', TeacherScheduleView.as_view(), name='teacher-schedule'),
    path('teacher/attendance/', TeacherAttendanceListView.as_view(), name='teacher-attendance'),
    path(
        'teacher/attendance/students/<int:student_pk>/',
        TeacherStudentAttendanceDetailView.as_view(),
        name='teacher-student-attendance',
    ),
    path(
        'teacher/students/<int:student_pk>/',
        TeacherStudentProfileView.as_view(),
        name='teacher-student-profile',
    ),
    path(
        'teacher/students/<int:student_pk>/quiz-access/<int:quiz_pk>/',
        TeacherQuizAssignmentToggleView.as_view(),
        name='teacher-quiz-assignment-toggle',
    ),
    path(
        'teacher/students/<int:student_pk>/mock-access/',
        TeacherMockAccessToggleView.as_view(),
        name='teacher-mock-access-toggle',
    ),
    path('teacher/attendance/session/', TeacherSessionAttendanceView.as_view(), name='teacher-attendance-session'),
    path('teacher/attendance/new/', TeacherAttendanceCreateView.as_view(), name='teacher-attendance-create'),
    path('teacher/scores/', TeacherScoresListView.as_view(), name='teacher-scores'),
    path('teacher/weekly-scores/', TeacherWeeklyScoresView.as_view(), name='teacher-weekly-scores'),
    path('teacher/notifications/', TeacherNotificationsView.as_view(), name='teacher-notifications'),
    path('teacher/scores/<int:result_pk>/', TeacherScoreDetailView.as_view(), name='teacher-score-detail'),
    path('teacher/quizzes/', TeacherQuizzesListView.as_view(), name='teacher-quizzes'),
    path(
        'teacher/quizzes/category/<int:category_pk>/',
        TeacherQuizCategoryDetailView.as_view(),
        name='teacher-quiz-category',
    ),
    path('teacher/quizzes/<int:pk>/', TeacherQuizDetailView.as_view(), name='teacher-quiz-detail'),
    path('teacher/quiz-results/', TeacherQuizResultsView.as_view(), name='teacher-quiz-results'),
    path(
        'teacher/quiz-results/<int:result_pk>/review/',
        TeacherQuizResultReviewView.as_view(),
        name='teacher-quiz-result-review',
    ),
    path('teacher/classrooms/', ClassroomsListView.as_view(), name='teacher-classrooms'),
    path('teacher/classrooms/<int:pk>/', ClassroomDetailView.as_view(), name='teacher-classroom-detail'),
    path('student/', StudentDashboardView.as_view(), name='student-dashboard'),
    path('student/schedule/', StudentScheduleView.as_view(), name='student-schedule'),
    path('student/lessons/<int:pk>/', StudentLessonDetailView.as_view(), name='student-lesson-detail'),
    path('student/lessons/', StudentLessonsView.as_view(), name='student-lessons'),
    path('student/scores/', StudentScoresView.as_view(), name='student-scores'),
    path('student/scores/quiz-history/', StudentQuizHistoryLoadView.as_view(), name='student-quiz-history-load'),
    path('student/notifications/', StudentNotificationsView.as_view(), name='student-notifications'),
    path('student/scores/<int:result_pk>/', StudentScoreDetailView.as_view(), name='student-score-detail'),
    path('student/quizzes/', StudentQuizzesView.as_view(), name='student-quizzes'),
    path(
        'student/quizzes/category/<int:category_pk>/',
        StudentQuizCategoryDetailView.as_view(),
        name='student-quiz-category',
    ),
    path('student/quizzes/<int:pk>/take/', StudentQuizTakeView.as_view(), name='student-quiz-take'),
    path('student/quizzes/<int:pk>/cancel/', StudentQuizCancelView.as_view(), name='student-quiz-cancel'),
    path('student/quizzes/<int:pk>/start/', StudentQuizStartView.as_view(), name='student-quiz-start'),
    path('student/quizzes/<int:pk>/submit/', StudentQuizSubmitView.as_view(), name='student-quiz-submit'),
    path('student/quizzes/<int:pk>/reading/', StudentReadingQuizTakeView.as_view(), name='student-reading-quiz-take'),
    path(
        'student/quizzes/<int:pk>/reading/submit/',
        StudentReadingQuizSubmitView.as_view(),
        name='student-reading-quiz-submit',
    ),
    path('student/quizzes/<int:pk>/manual/', StudentManualQuizTakeView.as_view(), name='student-manual-quiz-take'),
    path(
        'student/quizzes/<int:pk>/manual/submit/',
        StudentManualQuizSubmitView.as_view(),
        name='student-manual-quiz-submit',
    ),
    path('student/quizzes/<int:pk>/speaking/', StudentSpeakingQuizTakeView.as_view(), name='student-speaking-quiz-take'),
    path('student/quizzes/<int:pk>/speaking/submit/',
        StudentSpeakingQuizSubmitView.as_view(),
        name='student-speaking-quiz-submit',
    ),
    path('student/ielts-mock/', StudentIeltsMockLandingView.as_view(), name='student-ielts-mock'),
    path('student/ielts-mock/start/', StudentIeltsMockStartView.as_view(), name='student-ielts-mock-start'),
    path(
        'student/ielts-mock/<int:pk>/complete/',
        StudentIeltsMockCompleteView.as_view(),
        name='student-ielts-mock-complete',
    ),
    path('teacher/ielts-mock/<int:pk>/', TeacherIeltsMockDetailView.as_view(), name='teacher-ielts-mock-detail'),
    path('student/classrooms/', ClassroomsListView.as_view(), name='student-classrooms'),
    path('student/classrooms/<int:pk>/', ClassroomDetailView.as_view(), name='student-classroom-detail'),

    path('parent/', ParentDashboardView.as_view(), name='parent-dashboard'),
    path('parent/schedule/', ParentScheduleView.as_view(), name='parent-schedule'),
    path('parent/lessons/<int:pk>/', ParentLessonDetailView.as_view(), name='parent-lesson-detail'),
    path('parent/lessons/', ParentLessonsView.as_view(), name='parent-lessons'),
    path('parent/scores/', ParentScoresView.as_view(), name='parent-scores'),
    path('parent/ielts-mock/<int:pk>/', ParentIeltsMockDetailView.as_view(), name='parent-ielts-mock-detail'),
    path('parent/notifications/', ParentNotificationsView.as_view(), name='parent-notifications'),
    path('parent/scores/<int:result_pk>/', ParentScoreDetailView.as_view(), name='parent-score-detail'),
    path('parent/attendance/', ParentAttendanceView.as_view(), name='parent-attendance'),
    path('parent/classrooms/', ClassroomsListView.as_view(), name='parent-classrooms'),
    path('parent/classrooms/<int:pk>/', ClassroomDetailView.as_view(), name='parent-classroom-detail'),
]
