# Generated by Django 5.2.12 on 2026-04-01 20:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title_az', models.CharField(blank=True, max_length=120, null=True, verbose_name='Əsas başlıq (AZ)')),
                ('main_title_en', models.CharField(blank=True, max_length=120, null=True, verbose_name='Əsas başlıq (EN)')),
                ('main_title_ru', models.CharField(blank=True, max_length=120, null=True, verbose_name='Əsas başlıq (RU)')),
                ('second_title_az', models.CharField(blank=True, max_length=80, null=True, verbose_name='Alt başlıq (AZ)')),
                ('second_title_en', models.CharField(blank=True, max_length=80, null=True, verbose_name='Alt başlıq (EN)')),
                ('second_title_ru', models.CharField(blank=True, max_length=80, null=True, verbose_name='Alt başlıq (RU)')),
                ('description_az', models.TextField(validators=[django.core.validators.MaxLengthValidator(4000)], verbose_name='Text (AZ)')),
                ('description_en', models.TextField(validators=[django.core.validators.MaxLengthValidator(4000)], verbose_name='Text (EN)')),
                ('description_ru', models.TextField(validators=[django.core.validators.MaxLengthValidator(4000)], verbose_name='Text (RU)')),
            ],
            options={
                'verbose_name': 'Haqqımızda',
                'verbose_name_plural': 'Haqqımızda',
            },
        ),
        migrations.CreateModel(
            name='AcademyStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_one', models.PositiveIntegerField(verbose_name='Müştəri sayı')),
                ('value_two', models.PositiveIntegerField(verbose_name='Layihələr sayi')),
                ('value_three', models.PositiveIntegerField(verbose_name='Tərəfdaş sayi')),
            ],
            options={
                'verbose_name': 'Statistika',
                'verbose_name_plural': 'Statistikalar',
            },
        ),
        migrations.CreateModel(
            name='CareerOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('title_az', models.CharField(max_length=250, verbose_name='Vakansiya adı (AZ)')),
                ('title_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Vakansiya adı (EN)')),
                ('title_ru', models.CharField(blank=True, max_length=250, null=True, verbose_name='Vakansiya adı (RU)')),
                ('description_az', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(8000)], verbose_name='Vakansiya haqqında (AZ)')),
                ('description_en', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(8000)], verbose_name='Vakansiya haqqında (EN)')),
                ('description_ru', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(8000)], verbose_name='Vakansiya haqqında (RU)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Vakansiya aktivliyi')),
            ],
            options={
                'verbose_name': 'Vakansiya',
                'verbose_name_plural': 'Vakansiyalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_az', models.CharField(max_length=255, verbose_name='Ünvan (AZ)')),
                ('address_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ünvan (EN)')),
                ('address_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ünvan (RU)')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon')),
                ('whatsapp_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Whatsapp əlaqə nömrəsi')),
                ('whatsapp_number_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Whatsapp əlaqə nömrəsi 2')),
                ('phone_three', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('youtube', models.URLField(blank=True, null=True)),
                ('linkedn', models.URLField(blank=True, null=True, verbose_name='Linkedn')),
                ('tiktok', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Əlaqə',
                'verbose_name_plural': 'Əlaqələr',
            },
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, null=True, verbose_name='Ad Soyad')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Mail')),
                ('subject', models.CharField(blank=True, max_length=250, null=True, verbose_name='Subyekt')),
                ('info', models.TextField(blank=True, max_length=500, null=True, validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='Əlavə məlumat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False, verbose_name='Oxunulub')),
            ],
            options={
                'verbose_name': 'Mesaj',
                'verbose_name_plural': 'Mesajlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_az', models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.MaxLengthValidator(120)], verbose_name='Tərəfdaş adı (AZ)')),
                ('name_en', models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.MaxLengthValidator(120)], verbose_name='Tərəfdaş adı (EN)')),
                ('name_ru', models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.MaxLengthValidator(120)], verbose_name='Tərəfdaş adı (RU)')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='(Instagram)')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('linkedn', models.URLField(blank=True, null=True, verbose_name='Linkedn')),
                ('is_active', models.BooleanField(default=True, verbose_name='Əməkdaş aktivliyi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
            ],
            options={
                'verbose_name': 'Müəllim',
                'verbose_name_plural': 'Müəllimlər',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_az', models.CharField(max_length=250, verbose_name='Service adı (AZ)')),
                ('title_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Service adı (EN)')),
                ('title_ru', models.CharField(blank=True, max_length=250, null=True, verbose_name='Service adı (RU)')),
                ('description_az', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(800)], verbose_name='Service haqqında (AZ)')),
                ('description_en', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(800)], verbose_name='Service haqqında (EN)')),
                ('description_ru', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(800)], verbose_name='Service haqqında (RU)')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Servis aktivliyi')),
            ],
            options={
                'verbose_name': 'Proqram',
                'verbose_name_plural': 'Proqramlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Sual')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Sual',
                'verbose_name_plural': 'Suallar',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ad')),
                ('message', models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Rəy')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
            ],
            options={
                'verbose_name': 'Rəy',
                'verbose_name_plural': 'Rəylər',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('name_az', models.CharField(max_length=250, verbose_name='Ad (AZ)')),
                ('name_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ad (EN)')),
                ('name_ru', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ad (RU)')),
                ('description_az', models.TextField(validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Servis haqqında (AZ)')),
                ('description_en', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Servis haqqında (EN)')),
                ('description_ru', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Servis haqqında (RU)')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Url')),
                ('is_completed', models.BooleanField(blank=True, default=True, null=True, verbose_name='Servis tamamlanıb')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Servis aktivliyi')),
                ('speacial_project', models.BooleanField(blank=True, default=False, null=True, verbose_name='Seçilmiş (Featured)')),
                ('on_main_page', models.BooleanField(blank=True, default=False, null=True, verbose_name='Ana səhifədə göstər')),
                ('project_date', models.DateField(blank=True, null=True, verbose_name='Servis yaradılma tarixi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Servis',
                'verbose_name_plural': 'Servislər',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('name_az', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kateqoriya adı (AZ)')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kateqoriya adı (EN)')),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kateqoriya adı (RU)')),
            ],
            options={
                'verbose_name': 'Servis kateqoriyası',
                'verbose_name_plural': 'Servis kateqoriyaları',
            },
        ),
        migrations.CreateModel(
            name='Tagline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_az', models.TextField(validators=[django.core.validators.MaxLengthValidator(220)], verbose_name='Deviz cümləsi(AZ)')),
                ('text_en', models.TextField(validators=[django.core.validators.MaxLengthValidator(220)], verbose_name='Deviz cümləsi(EN)')),
                ('text_ru', models.TextField(validators=[django.core.validators.MaxLengthValidator(220)], verbose_name='Deviz cümləsi(RU)')),
            ],
            options={
                'verbose_name': 'Deviz',
                'verbose_name_plural': 'Deviz',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='Şəkil')),
                ('name', models.CharField(max_length=120, verbose_name='Ad')),
                ('role', models.CharField(max_length=120, verbose_name='Vəzifə')),
                ('description', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Təsvir')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
                ('tiktok', models.URLField(blank=True, null=True, verbose_name='TikTok')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='YouTube')),
            ],
            options={
                'verbose_name': 'Team üzvü',
                'verbose_name_plural': 'Team',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=200, verbose_name='Test adı')),
                ('description', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Açıqlama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testlər',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TestUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=100, verbose_name='Soyad')),
                ('number', models.CharField(max_length=30, verbose_name='Nömrə')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
            ],
            options={
                'verbose_name': 'Test istifadəçisi',
                'verbose_name_plural': 'Test istifadəçiləri',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Variant')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Düzgün cavab')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='projects.question')),
            ],
            options={
                'verbose_name': 'Cavab variantı',
                'verbose_name_plural': 'Cavab variantları',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Şəkil')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video')),
                ('is_home_page_background_image', models.BooleanField(default=False, verbose_name='Ana səhifəs üçün arxa plan şəkli')),
                ('is_about_page_background_image', models.BooleanField(default=False, verbose_name='Haqqımızda səhifəsi üçü arxa plan şəkli')),
                ('is_contact_page_background_image', models.BooleanField(default=False, verbose_name='Əlaqə səhifəsi üçün arxa plan şəkli')),
                ('is_project_page_background_image', models.BooleanField(default=False, verbose_name='Lahiyə səhifəsi üçün arxa plan şəkli')),
                ('is_vacany_page_background_image', models.BooleanField(default=False, verbose_name='Vakansiya səhifəsi üçün arxa plan şəkli')),
                ('is_service_page_background_image', models.BooleanField(default=False, verbose_name='Servis səhifəsi üçün arxa plan şəkli')),
                ('is_footer_background_image', models.BooleanField(default=False, verbose_name='Websiten-ın aşağı hissəsi üçün arxa plan şəkli')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Image yaradılma tarixi')),
                ('about', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='projects.about', verbose_name='Haqqımızda')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='projects.instructor', verbose_name='Əməkdaşlar')),
                ('vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='projects.careeropening', verbose_name='Vakansiyalar')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='projects.program', verbose_name='Servislər')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='projects.service', verbose_name='Lahiyə')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Medialar',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='projects.servicecategory', verbose_name='Servis kateqoriyası'),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='projects.test'),
        ),
        migrations.CreateModel(
            name='UserResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Bal')),
                ('level', models.CharField(max_length=50, verbose_name='Səviyyə')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='projects.test')),
                ('test_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='projects.testuser')),
            ],
            options={
                'verbose_name': 'Nəticə',
                'verbose_name_plural': 'Nəticələr',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, null=True, verbose_name='Ad Soyad')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Mail')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='Mobil Nömrə')),
                ('info', models.CharField(blank=True, max_length=250, null=True, verbose_name='Əlavə məlumat')),
                ('cv', models.FileField(upload_to='cvs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='CV')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('is_read', models.BooleanField(default=False, verbose_name='Oxunulub')),
                ('vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeal_set', to='projects.careeropening', verbose_name='Vakansiya')),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CV-lər',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('vacancy', 'email'), name='unique_email_per_vacancy'), models.UniqueConstraint(fields=('vacancy', 'phone_number'), name='unique_phone_per_vacancy')],
            },
        ),
    ]
