# Generated by Django 5.2.12 on 2026-04-01 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About', 'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ('id',), 'verbose_name': 'Option', 'verbose_name_plural': 'Options'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['-created_at'], 'verbose_name': 'Servis', 'verbose_name_plural': 'Proqramlar'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-created_at',), 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('id',), 'verbose_name': 'Team member', 'verbose_name_plural': 'Team'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ('-created_at',), 'verbose_name': 'Test', 'verbose_name_plural': 'Tests'},
        ),
        migrations.AlterModelOptions(
            name='testuser',
            options={'ordering': ('-created_at',), 'verbose_name': 'Test user', 'verbose_name_plural': 'Test users'},
        ),
        migrations.AlterModelOptions(
            name='userresult',
            options={'ordering': ('-created_at',), 'verbose_name': 'Result', 'verbose_name_plural': 'Results'},
        ),
        migrations.RemoveField(
            model_name='test',
            name='slug',
        ),
        migrations.AlterField(
            model_name='about',
            name='main_title_az',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Main title (AZ)'),
        ),
        migrations.AlterField(
            model_name='about',
            name='main_title_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Main title (EN)'),
        ),
        migrations.AlterField(
            model_name='about',
            name='main_title_ru',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Main title (RU)'),
        ),
        migrations.AlterField(
            model_name='about',
            name='second_title_az',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Subtitle (AZ)'),
        ),
        migrations.AlterField(
            model_name='about',
            name='second_title_en',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Subtitle (EN)'),
        ),
        migrations.AlterField(
            model_name='about',
            name='second_title_ru',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Subtitle (RU)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address_az',
            field=models.CharField(max_length=255, verbose_name='Address (AZ)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address (EN)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address (RU)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='linkedn',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_three',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone (additional)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='WhatsApp number'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='whatsapp_number_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='WhatsApp number 2'),
        ),
        migrations.AlterField(
            model_name='option',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Correct answer'),
        ),
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Option'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='team',
            name='role',
            field=models.CharField(max_length=120, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='test',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Test title'),
        ),
        migrations.AlterField(
            model_name='testuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='testuser',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='testuser',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='testuser',
            name='number',
            field=models.CharField(max_length=30, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='userresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='userresult',
            name='level',
            field=models.CharField(max_length=50, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='userresult',
            name='score',
            field=models.IntegerField(verbose_name='Score'),
        ),
    ]
