# Generated by Django 6.0.4 on 2026-06-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_coursepricepackage_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cover',
            field=models.ImageField(blank=True, help_text='Poster/thumbnail for the post or video.', null=True, upload_to='blog/covers/', verbose_name='Cover'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='video',
            field=models.FileField(blank=True, help_text='Optional video shown large at the top of the article.', null=True, upload_to='videos/blog/', verbose_name='Video'),
        ),
    ]
