# Generated by Django 5.2.15 on 2026-06-19 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_coursepricepackage_full_package_tabs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenttag',
            options={'ordering': ('order', 'name_az', 'id'), 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
