# Generated by Django 6.0.4 on 2026-06-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_tagline_text_i18n'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='apply_to_price_packages',
            field=models.BooleanField(default=False, help_text='When enabled, the discount percentage is deducted only from the selected price packages (homepage and course payment cards).', verbose_name='Apply discount to price packages'),
        ),
        migrations.AddField(
            model_name='sale',
            name='price_packages',
            field=models.ManyToManyField(blank=True, help_text='Optional. Select specific price packages when applying a package-level discount.', related_name='sales', to='projects.coursepricepackage', verbose_name='Price packages'),
        ),
    ]
