# Generated by Django 6.0.4 on 2026-06-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_sale_price_packages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='apply_to_price_packages',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='apply_to_service_prices',
        ),
        migrations.AlterField(
            model_name='sale',
            name='price_packages',
            field=models.ManyToManyField(blank=True, help_text='Optional. Selected price cards get the discount (homepage carousel and course page).', related_name='sales', to='projects.coursepricepackage', verbose_name='Price packages'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='Optional. Selected courses get the discount on all their price packages.', related_name='sales', to='projects.service', verbose_name='Services'),
        ),
    ]
