# Generated by Django 5.2.12 on 2026-04-06 08:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_servicehighlight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ('-created_at',), 'verbose_name': 'Instructor', 'verbose_name_plural': 'Instructors'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'Media', 'verbose_name_plural': 'Media'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name': 'Service category', 'verbose_name_plural': 'Service categories'},
        ),
        migrations.AlterModelOptions(
            name='tagline',
            options={'verbose_name': 'Tagline (home hero)', 'verbose_name_plural': 'Tagline (Only one)'},
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='full_name',
            field=models.CharField(blank=True, null=True, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='info',
            field=models.TextField(blank=True, max_length=500, null=True, validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='Additional info'),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Read'),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='subject',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='linkedn',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='name_az',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.MaxLengthValidator(120)], verbose_name='Partner name (AZ)'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='name_en',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.MaxLengthValidator(120)], verbose_name='Partner name (EN)'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='name_ru',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.MaxLengthValidator(120)], verbose_name='Partner name (RU)'),
        ),
        migrations.AlterField(
            model_name='media',
            name='about',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='projects.about', verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='media',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='media',
            name='is_about_page_background_image',
            field=models.BooleanField(default=False, verbose_name='About page background image'),
        ),
        migrations.AlterField(
            model_name='media',
            name='is_contact_page_background_image',
            field=models.BooleanField(default=False, verbose_name='Contact page background image'),
        ),
        migrations.AlterField(
            model_name='media',
            name='is_home_page_background_image',
            field=models.BooleanField(default=False, verbose_name='Home page background image'),
        ),
        migrations.AlterField(
            model_name='media',
            name='is_project_page_background_image',
            field=models.BooleanField(default=False, verbose_name='Project page background image'),
        ),
        migrations.AlterField(
            model_name='media',
            name='is_service_page_background_image',
            field=models.BooleanField(default=False, verbose_name='Service page background image'),
        ),
        migrations.AlterField(
            model_name='media',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='projects.instructor', verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name_az',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Category name (AZ)'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Category name (EN)'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Category name (RU)'),
        ),
        migrations.AlterField(
            model_name='test',
            name='description_en',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Description (EN)'),
        ),
        migrations.AlterField(
            model_name='test',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Test title (EN)'),
        ),
        migrations.AlterField(
            model_name='userresult',
            name='first_name',
            field=models.CharField(default='yes', max_length=100, verbose_name='First name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userresult',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='userresult',
            name='number',
            field=models.CharField(default='', max_length=30, verbose_name='Phone number'),
            preserve_default=False,
        ),
    ]
