# Generated by Django 5.2.12 on 2026-04-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_merge_0018_conflict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicehighlight',
            name='description_az',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Description (AZ)'),
        ),
        migrations.AlterField(
            model_name='servicehighlight',
            name='description_en',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Description (EN)'),
        ),
        migrations.AlterField(
            model_name='servicehighlight',
            name='description_ru',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Description (RU)'),
        ),
        migrations.AlterField(
            model_name='servicehighlight',
            name='title_az',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title (AZ)'),
        ),
        migrations.AlterField(
            model_name='servicehighlight',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title (EN)'),
        ),
        migrations.AlterField(
            model_name='servicehighlight',
            name='title_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title (RU)'),
        ),
    ]
