# Generated by Django 6.0.4 on 2026-04-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_abroadmodel_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='image_focal_point',
            field=models.CharField(blank=True, default='center center', max_length=20, verbose_name='Image focal point'),
        ),
    ]
