# Generated by Django 5.2.12 on 2026-04-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_media_image_focal_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicehighlight',
            name='title_az',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Title (AZ)'),
        ),
        migrations.AlterField(
            model_name='servicehighlight',
            name='title_en',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Title (EN)'),
        ),
        migrations.AlterField(
            model_name='servicehighlight',
            name='title_ru',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Title (RU)'),
        ),
    ]
