# Generated by Django 5.2.15 on 2026-07-13 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_alter_tagline_page_portal_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='bullet_list_az',
            field=models.TextField(blank=True, help_text='One item per line (bullet list).', null=True, validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Bullet list (AZ)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='bullet_list_en',
            field=models.TextField(blank=True, help_text='One item per line (bullet list).', null=True, validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Bullet list (EN)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='bullet_list_ru',
            field=models.TextField(blank=True, help_text='One item per line (bullet list).', null=True, validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Bullet list (RU)'),
        ),
    ]
