# Generated by Django 6.1 on 2026-08-08 06:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_alter_service_bullet_list_az_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full name')),
                ('program_az', models.CharField(blank=True, max_length=200, verbose_name='Training program (AZ)')),
                ('program_en', models.CharField(blank=True, max_length=200, verbose_name='Training program (EN)')),
                ('program_ru', models.CharField(blank=True, max_length=200, verbose_name='Training program (RU)')),
                ('code', models.CharField(db_index=True, help_text='Mobile number or unique lookup code.', max_length=64, unique=True, verbose_name='Code')),
                ('score', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Score')),
                ('rank', models.PositiveIntegerField(default=0, help_text='Leave as-is when using automatic ranking.', verbose_name='Rank')),
                ('show', models.BooleanField(default=False, help_text='If enabled, this person can appear in the public Top 5 list.', verbose_name='Show in Top 5')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Mock test result',
                'verbose_name_plural': 'Mock test results',
                'ordering': ('rank', '-score', 'full_name'),
            },
        ),
    ]
