# Generated by Django 6.0.4 on 2026-04-08 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_remove_media_image_focal_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Slide image')),
                ('heading_small_az', models.CharField(blank=True, max_length=150, verbose_name='Small heading (AZ)')),
                ('heading_small_en', models.CharField(blank=True, max_length=150, verbose_name='Small heading (EN)')),
                ('heading_small_ru', models.CharField(blank=True, max_length=150, verbose_name='Small heading (RU)')),
                ('heading_main_az', models.CharField(blank=True, max_length=200, verbose_name='Main heading (AZ)')),
                ('heading_main_en', models.CharField(blank=True, max_length=200, verbose_name='Main heading (EN)')),
                ('heading_main_ru', models.CharField(blank=True, max_length=200, verbose_name='Main heading (RU)')),
                ('body_az', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(400)], verbose_name='Description (AZ)')),
                ('body_en', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(400)], verbose_name='Description (EN)')),
                ('body_ru', models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(400)], verbose_name='Description (RU)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='tagline',
            options={'verbose_name': 'Tagline', 'verbose_name_plural': 'Tagline)'},
        ),
    ]
