# Generated by Django 6.0.4 on 2026-04-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_abroadmodel_detail_page_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Service category', 'verbose_name_plural': 'Service categories'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Team member', 'verbose_name_plural': 'Team'},
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='team',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
    ]
