# Generated by Django 5.2.12 on 2026-04-08 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_add_order_to_servicecategory_and_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
    ]
