# Generated by Django 5.2.12 on 2026-04-08 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_alter_servicecategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ('-order', 'id'), 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('-order', 'id'), 'verbose_name': 'Team member', 'verbose_name_plural': 'Team'},
        ),
    ]
