# Generated by Django 6.0.4 on 2026-04-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_alter_servicecategory_options_alter_team_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Team member', 'verbose_name_plural': 'Team'},
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='duration_months_az',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Duration (AZ)'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='duration_months_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Duration (EN)'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='duration_months_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Duration (RU)'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='lesson_hours_az',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lesson hours (AZ)'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='lesson_hours_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lesson hours (EN)'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='lesson_hours_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lesson hours (RU)'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='has_certificate',
            field=models.BooleanField(default=True, verbose_name='Certificate'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='is_offline',
            field=models.BooleanField(default=True, verbose_name='Offline'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='is_online',
            field=models.BooleanField(default=True, verbose_name='Online'),
        ),
    ]
