# Generated by Django 5.2.12 on 2026-04-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_add_course_detail_fields_to_servicecategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='lesson_hours_az',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='lesson_hours_en',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='lesson_hours_ru',
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='lesson_count_az',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lesson counts (AZ)'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='lesson_count_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lesson counts (EN)'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='lesson_count_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lesson counts (RU)'),
        ),
    ]
