# Generated by Django 6.0.4 on 2026-04-29 09:28

from django.db import migrations, models


def seed_site_faq_entries(apps, schema_editor):
    SiteFaqEntry = apps.get_model('projects', 'SiteFaqEntry')
    if SiteFaqEntry.objects.exists():
        return
    payload = [
        {
            'question_az': 'Onlayn və mərkəzdə (əyanı) dərslər təklif edirsiniz?',
            'question_en': 'Do you offer online and in-person lessons?',
            'question_ru': 'Есть ли онлайн и очные занятия?',
            'answer_az': 'Bəli. Bir çox proqramlar onlayn və Bakıdakı mərkəzdə keçirilir — sizə uyğun formatı soruşun.',
            'answer_en': 'Yes. Many programs run online and at our center in Baku—ask which format suits you best.',
            'answer_ru': 'Да. Многие программы проходят онлайн и в нашем центре в Баку — уточните удобный формат.',
        },
        {
            'question_az': 'Hansı imtahanlara hazırlıq verirsiniz?',
            'question_en': 'Which exams do you prepare for?',
            'question_ru': 'К каким экзаменам готовите?',
            'answer_az': 'Məqsədlərinizdən asılı olaraq IELTS, GMAT, GRE, YÖS, ALES və digər istiqamətlərdə dəstək veririk.',
            'answer_en': 'We support IELTS, GMAT, GRE, YÖS, ALES, and other tracks depending on your target.',
            'answer_ru': 'Готовим к IELTS, GMAT, GRE, YÖS, ALES и другим направлениям в зависимости от цели.',
        },
        {
            'question_az': 'Xaricdə təhsil dəstəyi necə işləyir?',
            'question_en': 'How does study abroad support work?',
            'question_ru': 'Как устроена поддержка при поступлении за рубеж?',
            'answer_az': 'Universitetlərin seçilməsi, sənədlər, motivasiya məktubları və zaman cədvəli üzrə kömək edirik.',
            'answer_en': 'We help with shortlisting universities, documents, motivation letters, and timeline planning.',
            'answer_ru': 'Помогаем со списком вузов, документами, мотивационными письмами и сроками.',
        },
        {
            'question_az': 'Məsləhət necə sifariş olunur?',
            'question_en': 'How can I book a consultation?',
            'question_ru': 'Как записаться на консультацию?',
            'answer_az': 'Əlaqə forması, zəng və ya WhatsApp ilə yazın — adətən bir iş günü ərzində cavab veririk.',
            'answer_en': 'Use the contact form, call us, or message on WhatsApp—we usually reply within one business day.',
            'answer_ru': 'Напишите через форму контактов, позвоните или в WhatsApp — обычно отвечаем в течение рабочего дня.',
        },
        {
            'question_az': 'Ödənişi hissə-hissə etmək mümkündür?',
            'question_en': 'Are payment plans available?',
            'question_ru': 'Возможна ли оплата частями?',
            'answer_az': 'Hissə-hissə ödəniş proqramdan asılıdır; qoşulmazdan əvvəl seçimləri aydın şəkildə izah edirik.',
            'answer_en': 'Installment options depend on the program; we explain the choices clearly before you enroll.',
            'answer_ru': 'Рассрочка зависит от программы; перед зачислением чётко объясняем варианты.',
        },
    ]
    for order, row in enumerate(payload):
        SiteFaqEntry.objects.create(order=order, is_active=True, **row)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_abroadmodel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteFaqEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_az', models.CharField(max_length=500, verbose_name='Question (AZ)')),
                ('question_en', models.CharField(max_length=500, verbose_name='Question (EN)')),
                ('question_ru', models.CharField(max_length=500, verbose_name='Question (RU)')),
                ('answer_az', models.TextField(verbose_name='Answer (AZ)')),
                ('answer_en', models.TextField(verbose_name='Answer (EN)')),
                ('answer_ru', models.TextField(verbose_name='Answer (RU)')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Site FAQ entry',
                'verbose_name_plural': 'Site FAQ entries',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.RunPython(seed_site_faq_entries, noop_reverse),
    ]
