# Generated by Django 5.2.13 on 2026-04-29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_sitefaqentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(
                default=5,
                help_text='Stars from 1 to 5.',
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name='Rating (1–5)',
            ),
        ),
    ]
