# Generated by Django 5.2

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_review_video_embed_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='video_embed_url',
        ),
    ]
