# Generated by Django 5.2

from django.db import migrations, models
from django.utils.text import slugify


def _team_table(schema_editor, apps):
    Team = apps.get_model('projects', 'Team')
    return Team._meta.db_table


def _populate_slugs(Team):
    for obj in Team.objects.all().order_by('id'):
        base = slugify((obj.name or '').strip()) or 'member'
        base = base[:140]
        slug = base
        n = 2
        while Team.objects.filter(slug=slug).exclude(pk=obj.pk).exists():
            suffix = f'-{n}'
            slug = (base[: max(1, 150 - len(suffix))] + suffix)[:150]
            n += 1
        Team.objects.filter(pk=obj.pk).update(slug=slug)


def setup_team_slug_column(apps, schema_editor):
    """DB-only; must not use Team.slug (SeparateDatabaseAndState passes pre-AddField state)."""
    table = _team_table(schema_editor, apps)
    q_table = schema_editor.quote_name(table)
    q_slug = schema_editor.quote_name('slug')
    conn = schema_editor.connection
    with conn.cursor() as c:
        if conn.vendor == 'postgresql':
            c.execute(
                f'ALTER TABLE {q_table} ADD COLUMN IF NOT EXISTS {q_slug} varchar(150) NULL'
            )
            c.execute('DROP INDEX IF EXISTS projects_team_slug_b8777a03_like')
            c.execute(
                'ALTER TABLE %s DROP CONSTRAINT IF EXISTS projects_team_slug_key'
                % q_table
            )
        else:
            c.execute(f'PRAGMA table_info({table})')
            columns = [row[1] for row in c.fetchall()]
            if 'slug' not in columns:
                c.execute(
                    f'ALTER TABLE {q_table} ADD COLUMN {q_slug} varchar(150) NULL'
                )


def populate_team_slugs(apps, schema_editor):
    Team = apps.get_model('projects', 'Team')
    _populate_slugs(Team)


def finalize_team_slug_column(apps, schema_editor):
    """ORM not required; state already has slug after SeparateDatabaseAndState."""
    table = _team_table(schema_editor, apps)
    q_table = schema_editor.quote_name(table)
    q_slug = schema_editor.quote_name('slug')
    conn = schema_editor.connection
    with conn.cursor() as c:
        if conn.vendor == 'postgresql':
            c.execute(f'ALTER TABLE {q_table} ALTER COLUMN {q_slug} SET NOT NULL')
            c.execute(
                """
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint WHERE conname = 'projects_team_slug_key'
                    ) THEN
                        ALTER TABLE """
                + q_table
                + """
                        ADD CONSTRAINT projects_team_slug_key UNIQUE (slug);
                    END IF;
                END $$;
                """
            )
        else:
            c.execute(
                f'CREATE UNIQUE INDEX IF NOT EXISTS projects_team_slug_uniq '
                f'ON {q_table} ({q_slug})'
            )


def reverse_finalize_team_slug(apps, schema_editor):
    q_table = schema_editor.quote_name(_team_table(schema_editor, apps))
    q_slug = schema_editor.quote_name('slug')
    conn = schema_editor.connection
    with conn.cursor() as c:
        if conn.vendor == 'postgresql':
            c.execute(
                'ALTER TABLE %s DROP CONSTRAINT IF EXISTS projects_team_slug_key'
                % q_table
            )
            c.execute(f'ALTER TABLE {q_table} ALTER COLUMN {q_slug} DROP NOT NULL')
        else:
            c.execute('DROP INDEX IF EXISTS projects_team_slug_uniq')


def reverse_setup_team_slug(apps, schema_editor):
    q_table = schema_editor.quote_name(_team_table(schema_editor, apps))
    q_slug = schema_editor.quote_name('slug')
    conn = schema_editor.connection
    if conn.vendor == 'postgresql':
        with conn.cursor() as c:
            c.execute('DROP INDEX IF EXISTS projects_team_slug_b8777a03_like')
            c.execute(f'ALTER TABLE {q_table} DROP COLUMN IF EXISTS {q_slug}')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0046_remove_review_video_embed_url'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='team',
                    name='slug',
                    field=models.SlugField(
                        max_length=150, unique=True, verbose_name='URL slug'
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(setup_team_slug_column, reverse_setup_team_slug),
            ],
        ),
        migrations.RunPython(populate_team_slugs, noop_reverse),
        migrations.RunPython(finalize_team_slug_column, reverse_finalize_team_slug),
    ]
