# Generated by Django 5.2

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_team_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='university',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True, verbose_name='URL slug'),
        ),
        migrations.AddField(
            model_name='university',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='university',
            name='study_abroad',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='universities',
                to='projects.abroadmodel',
                verbose_name='Study abroad country',
            ),
        ),
    ]
