# Generated by Django 5.2.10 on 2026-05-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0056_blogpostimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='on_main_page',
            field=models.BooleanField(default=False, help_text='Show this post on the homepage.', verbose_name='On main page'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='on_top',
            field=models.BooleanField(default=False, help_text='Pinned posts appear first (max 2 shown as featured).', verbose_name='On top'),
        ),
    ]
