# Generated by Django 5.2.10 on 2026-05-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0060_servicecategory_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='on_top',
            field=models.BooleanField(default=False, help_text='Pinned posts appear first (maximum 2 allowed).', verbose_name='On top'),
        ),
    ]
