# Generated by Django 5.2.10 on 2026-05-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0064_servicecategory_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Mobile number'),
        ),
    ]
