# Generated by Django 6.0.4 on 2026-05-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0065_alter_review_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='video',
            field=models.FileField(blank=True, help_text='Promotional video shown on the About page.', null=True, upload_to='videos/about/', verbose_name='Video'),
        ),
        migrations.AddField(
            model_name='about',
            name='video_cover',
            field=models.ImageField(blank=True, help_text='Poster image displayed before the video is played.', null=True, upload_to='images/about_video_cover/', verbose_name='Video cover'),
        ),
    ]
