# Generated by Django 6.0.4 on 2026-05-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0066_about_video_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutGalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/about_gallery/', verbose_name='Image')),
                ('name_az', models.CharField(max_length=120, verbose_name='Name (AZ)')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='Name (EN)')),
                ('name_ru', models.CharField(blank=True, max_length=120, verbose_name='Name (RU)')),
                ('role_az', models.CharField(blank=True, max_length=160, verbose_name='Role (AZ)')),
                ('role_en', models.CharField(blank=True, max_length=160, verbose_name='Role (EN)')),
                ('role_ru', models.CharField(blank=True, max_length=160, verbose_name='Role (RU)')),
                ('tag_az', models.CharField(blank=True, max_length=60, verbose_name='Tag (AZ)')),
                ('tag_en', models.CharField(blank=True, max_length=60, verbose_name='Tag (EN)')),
                ('tag_ru', models.CharField(blank=True, max_length=60, verbose_name='Tag (RU)')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'About gallery item',
                'verbose_name_plural': 'About gallery items',
                'ordering': ('order', 'id'),
            },
        ),
    ]
