# Generated by Django 6.0.4 on 2026-06-04 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0069_about_media_gallery_strip'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePricePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_az', models.CharField(max_length=255, verbose_name='Name (AZ)')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='Name (EN)')),
                ('name_ru', models.CharField(blank=True, max_length=255, verbose_name='Name (RU)')),
                ('duration', models.CharField(blank=True, help_text='e.g. 3 months', max_length=100, verbose_name='Duration')),
                ('lesson_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of lessons')),
                ('hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Hours')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price (AZN)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_packages', to='projects.servicecategory', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Course price package',
                'verbose_name_plural': 'Course price packages',
                'ordering': ('order', 'id'),
            },
        ),
    ]
