# Generated by Django 5.2.10 on 2026-06-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0073_servicecategory_card_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepricepackage',
            name='lesson_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Duration of a single lesson in minutes.', null=True, verbose_name='Minutes per lesson'),
        ),
    ]
