# Generated by Django 6.0.4 on 2026-06-07 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0075_bump_cache_after_service_card_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='message',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(276)], verbose_name='Review'),
        ),
    ]
