# Generated by Django 6.0.4 on 2026-06-11 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0078_rename_service_remove_highlight_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_az', models.CharField(max_length=255, verbose_name='Title (AZ)')),
                ('ad_en', models.CharField(blank=True, max_length=255, verbose_name='Title (EN)')),
                ('ad_ru', models.CharField(blank=True, max_length=255, verbose_name='Title (RU)')),
                ('melumat_az', models.TextField(blank=True, verbose_name='Description (AZ)')),
                ('melumat_en', models.TextField(blank=True, verbose_name='Description (EN)')),
                ('melumat_ru', models.TextField(blank=True, verbose_name='Description (RU)')),
                ('percent', models.PositiveSmallIntegerField(help_text='Discount percentage from 1 to 100.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Discount (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('services', models.ManyToManyField(blank=True, help_text='Optional. Leave empty for a general promotion.', related_name='sales', to='projects.service', verbose_name='Services')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'ordering': ('-created_at',),
            },
        ),
    ]
