# Generated by Django 6.0.4 on 2026-06-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0079_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='apply_to_service_prices',
            field=models.BooleanField(default=False, help_text='When enabled, the discount percentage is deducted from the prices of the selected services.', verbose_name='Apply discount to service prices'),
        ),
    ]
