# Generated by Django 5.2.15 on 2026-06-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0081_rename_sale_fields_to_english'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='name_az',
            field=models.CharField(max_length=255, verbose_name='Name (AZ)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name (EN)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name (RU)'),
        ),
    ]
