# Generated by Django 6.0.4 on 2026-06-11 08:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0082_alter_sale_name_az_alter_sale_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='description_az',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Description (AZ)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Description (EN)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='description_ru',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Description (RU)'),
        ),
    ]
