# Generated by Django 5.2.15 on 2026-06-16 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('client_order_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='AZN', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Successful'), ('cancelled', 'Cancelled'), ('declined', 'Declined'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('product_type', models.CharField(choices=[('course', 'Course'), ('generic', 'Generic')], db_index=True, default='generic', max_length=20)),
                ('buyer_email', models.EmailField(blank=True, max_length=254)),
                ('buyer_name', models.CharField(blank=True, max_length=255)),
                ('buyer_phone', models.CharField(blank=True, max_length=30)),
                ('enrollment_completed_at', models.DateTimeField(blank=True, null=True)),
                ('callback_up', models.TextField(blank=True)),
                ('callback_payload', models.JSONField(blank=True, default=dict)),
                ('callback_received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='projects.service', verbose_name='Course')),
                ('price_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='projects.coursepricepackage', verbose_name='Price package')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('buyer_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20)),
                ('buyer_phone', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='projects.service')),
                ('price_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='projects.coursepricepackage', verbose_name='Price package')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Course enrollment',
                'verbose_name_plural': 'Course enrollments',
                'ordering': ['-created_at'],
            },
        ),
    ]
