# Generated by Django 5.2.10 on 2026-06-01 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_callback_payload'),
        ('projects', '0069_about_media_gallery_strip'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='buyer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='payment',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='projects.servicecategory', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='payment',
            name='enrollment_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='product_type',
            field=models.CharField(choices=[('course', 'Course'), ('generic', 'Generic')], db_index=True, default='generic', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Successful'), ('cancelled', 'Cancelled'), ('declined', 'Declined'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('buyer_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='projects.servicecategory')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Course enrollment',
                'verbose_name_plural': 'Course enrollments',
                'ordering': ['-created_at'],
            },
        ),
    ]
