# Generated by Django 5.2.15 on 2026-06-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_courseenrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='buyer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='payment',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='buyer_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
