# Generated by Django 6.0.4 on 2026-06-04 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_buyer_phone_courseenrollment_buyer_phone'),
        ('projects', '0070_course_price_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='price_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='projects.coursepricepackage', verbose_name='Price package'),
        ),
        migrations.AddField(
            model_name='payment',
            name='price_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='projects.coursepricepackage', verbose_name='Price package'),
        ),
    ]
