# Generated by Django 6.0.4 on 2026-06-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_contract_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='buyer_birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AddField(
            model_name='payment',
            name='buyer_birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
    ]
