# Generated by Django 5.2.15 on 2026-06-29 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_buyer_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseenrollment',
            name='buyer_birth_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='buyer_birth_date',
        ),
    ]
