# Generated by Django 6.0.4 on 2026-07-09 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_remove_courseenrollment_buyer_birth_date_and_more'),
        ('portals', '0075_customer_mock_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='portals.customerprofile', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='payment',
            name='mock_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='portals.mocktestpackage', verbose_name='Mock test package'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='product_type',
            field=models.CharField(choices=[('course', 'Course'), ('mock_test', 'Mock test'), ('generic', 'Generic')], db_index=True, default='generic', max_length=20),
        ),
    ]
