KEYS = {8: {'math_m1': ['C',
                 'C',
                 'D',
                 'D',
                 'A',
                 '0.2; 1/5',
                 '240',
                 'A',
                 'B',
                 'B',
                 'B',
                 'D',
                 '25',
                 '6',
                 'C',
                 'D',
                 'A',
                 'D',
                 'C',
                 '7',
                 '182',
                 'D',
                 'B',
                 'C',
                 'C',
                 'B',
                 '284/3; 94.66; 94.67'],
     'math_m2': ['C',
                 'C',
                 'D',
                 'C',
                 'D',
                 '9',
                 '68',
                 'B',
                 'D',
                 'D',
                 'C',
                 'B',
                 '986',
                 '24',
                 'D',
                 'D',
                 'A',
                 'B',
                 'A',
                 '46',
                 '1.8; 9/5',
                 'A',
                 'B',
                 'C',
                 'B',
                 'D',
                 '168'],
     'rw_m1': 'BDACCCDAADBCAADCADCBBADCCDABCACAD',
     'rw_m2': 'BABDDACAADBCDBCACDABCACABAAACBDBD'},
 9: {'math_m1': ['B',
                 'C',
                 'B',
                 'A',
                 'A',
                 '9',
                 '224',
                 'A',
                 'C',
                 'B',
                 'A',
                 'B',
                 '40',
                 '14',
                 'C',
                 'D',
                 'B',
                 'D',
                 'D',
                 '52',
                 '-3',
                 'B',
                 'D',
                 'A',
                 'D',
                 'B',
                 '1260'],
     'math_m2': ['B',
                 'B',
                 'D',
                 'B',
                 'D',
                 '70',
                 '1',
                 'D',
                 'A',
                 'D',
                 'C',
                 'D',
                 '45',
                 '2; -12',
                 'B',
                 'C',
                 'B',
                 'B',
                 'C',
                 '410',
                 '-19',
                 'D',
                 'D',
                 'A',
                 'C',
                 'D',
                 '50'],
     'rw_m1': 'ADCCBCAACADCDCADBAAABCCCABABDBBAC',
     'rw_m2': 'BCBBCDDDAADADCCDBDCDCCBDCCCABCDCB'},
 10: {'math_m1': ['C',
                  'A',
                  'D',
                  'A',
                  'D',
                  '77',
                  '25',
                  'C',
                  'B',
                  'B',
                  'B',
                  'B',
                  '1',
                  '76',
                  'A',
                  'D',
                  'D',
                  'A',
                  'A',
                  '35',
                  '113',
                  'A',
                  'C',
                  'C',
                  'D',
                  'A',
                  '29/3; 9.666; 9.667'],
      'math_m2': ['D',
                  'A',
                  'D',
                  'D',
                  'A',
                  '79',
                  '2',
                  'D',
                  'D',
                  'B',
                  'A',
                  'C',
                  '41',
                  '11875',
                  'B',
                  'B',
                  'B',
                  'A',
                  'C',
                  '5',
                  '0.25; 1/4',
                  'D',
                  'C',
                  'C',
                  'D',
                  'B',
                  '104'],
      'rw_m1': 'ABBACBDDCCCBAAAACDCBACCCCCABBBBCC',
      'rw_m2': 'AADAADBBDDDABADAAADBDCADAABDADDAC'},
 11: {'math_m1': ['D',
                  'A',
                  'C',
                  'A',
                  'B',
                  '75',
                  '30',
                  'A',
                  'C',
                  'C',
                  'D',
                  'B',
                  '13',
                  '15000',
                  'A',
                  'A',
                  'C',
                  'B',
                  'D',
                  '100',
                  '29',
                  'B',
                  'B',
                  'A',
                  'C',
                  'B',
                  '3331'],
      'math_m2': ['C',
                  'B',
                  'D',
                  'D',
                  'A',
                  '8.6; 43/5',
                  '3600',
                  'A',
                  'B',
                  'D',
                  'C',
                  'A',
                  '45',
                  '13',
                  'B',
                  'C',
                  'D',
                  'B',
                  'A',
                  '.5061; .5062; 41/81',
                  '1512/5; 302.4',
                  'C',
                  'A',
                  'B',
                  'B',
                  'D',
                  '157.8; 789/5'],
      'rw_m1': 'ACDDABBDDCBDADBADDDDABBADDDAACADB',
      'rw_m2': 'CCCDBBBABCBDCBCCAABBBBBBABDBCBCAA'}}
