# Generated by Django 6.0.4 on 2026-06-23 13:26

import django.db.models.deletion
import portals.models.profile_models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='portals/lessons/pdf/', verbose_name='PDF file')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portals/lessons/images/', verbose_name='Image')),
                ('lesson_type', models.CharField(choices=[('group', 'Group'), ('individual', 'Individual')], default='group', max_length=16, verbose_name='Lesson type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(max_length=32, verbose_name='Course type')),
                ('topic', models.CharField(max_length=255, verbose_name='Topic')),
                ('level', models.CharField(max_length=100, verbose_name='Level')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('course_type', models.CharField(choices=[('general_english', 'General English'), ('speaking', 'Speaking'), ('ielts', 'IELTS'), ('gmat', 'GMAT'), ('gre', 'GRE'), ('sat', 'SAT'), ('yos', 'YÖS'), ('ales', 'ALES'), ('study_abroad', 'Study abroad'), ('other', 'Other')], db_index=True, max_length=32, verbose_name='Course type')),
                ('level', models.CharField(blank=True, help_text='e.g. Beginner, Intermediate, Band 6.5 target', max_length=100, verbose_name='Level')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('max_students', models.PositiveIntegerField(default=12, verbose_name='Max students')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Study group',
                'verbose_name_plural': 'Study groups',
                'ordering': ('-is_active', 'name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('media_type', models.CharField(choices=[('none', 'None'), ('image', 'Image'), ('video', 'Video')], default='none', max_length=16, verbose_name='Media type')),
                ('media_url', models.URLField(blank=True, verbose_name='Media URL')),
                ('answer_options', models.JSONField(default=list, help_text='List of answer choices shown to the student.', verbose_name='Answer options')),
                ('correct_answer', models.CharField(max_length=500, verbose_name='Correct answer')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='portals.quiz', verbose_name='Quiz')),
            ],
            options={
                'verbose_name': 'Quiz question',
                'verbose_name_plural': 'Quiz questions',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('enrollment_date', models.DateField(blank=True, null=True, verbose_name='Enrollment date')),
                ('phone', models.CharField(blank=True, max_length=30, validators=[portals.utils.normalize_phone_number.phone_number_validator], verbose_name='Phone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='portals.studygroup', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Student profile',
                'verbose_name_plural': 'Student profiles',
                'ordering': ('last_name', 'first_name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_type', models.CharField(choices=[('homework', 'Homework'), ('exam', 'Exam'), ('quiz', 'Quiz')], db_index=True, max_length=16, verbose_name='Score type')),
                ('value', models.FloatField(verbose_name='Value')),
                ('max_value', models.FloatField(verbose_name='Max value')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('lesson', models.ForeignKey(blank=True, help_text='Optional — homework and exams may not map to a single lesson.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores', to='portals.lesson', verbose_name='Lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='portals.studentprofile', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Score',
                'verbose_name_plural': 'Scores',
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_answers', models.JSONField(default=dict, help_text='Map of question id → selected answer.', verbose_name='Given answers')),
                ('total_score', models.FloatField(verbose_name='Total score')),
                ('duration_sec', models.PositiveIntegerField(verbose_name='Duration (seconds)')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Completed at')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='portals.quiz', verbose_name='Quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to='portals.studentprofile', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Quiz result',
                'verbose_name_plural': 'Quiz results',
                'ordering': ('-completed_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('phone', models.CharField(blank=True, max_length=30, validators=[portals.utils.normalize_phone_number.phone_number_validator], verbose_name='Phone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='portals.studentprofile', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Parent profile',
                'verbose_name_plural': 'Parent profiles',
                'ordering': ('last_name', 'first_name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='Weekday')),
                ('start_time', models.TimeField(verbose_name='Start time')),
                ('duration_min', models.PositiveIntegerField(verbose_name='Duration (minutes)')),
                ('room_or_link', models.CharField(blank=True, max_length=500, verbose_name='Room or link')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='portals.studygroup', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'ordering': ('weekday', 'start_time', 'id'),
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='portals.studygroup', verbose_name='Group'),
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='Specialization')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Teacher profile',
                'verbose_name_plural': 'Teacher profiles',
                'ordering': ('last_name', 'first_name', 'id'),
            },
        ),
        migrations.AddField(
            model_name='studygroup',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='portals.teacherprofile', verbose_name='Teacher'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quizzes', to='portals.teacherprofile', verbose_name='Teacher'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='portals.teacherprofile', verbose_name='Teacher'),
        ),
        migrations.CreateModel(
            name='VideoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('youtube_url', models.URLField(verbose_name='YouTube URL')),
                ('lesson_date', models.DateField(verbose_name='Lesson date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_records', to='portals.studygroup', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Video record',
                'verbose_name_plural': 'Video records',
                'ordering': ('-lesson_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(help_text='Concrete date of the class session (schedule defines the recurring slot).', verbose_name='Session date')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], max_length=16, verbose_name='Status')),
                ('marked_at', models.DateTimeField(auto_now_add=True, verbose_name='Marked at')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='portals.schedule', verbose_name='Schedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='portals.studentprofile', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance records',
                'ordering': ('-session_date', '-marked_at', 'id'),
                'constraints': [models.UniqueConstraint(fields=('schedule', 'student', 'session_date'), name='portals_attendance_unique_session')],
            },
        ),
    ]
