# Generated by Django 6.0.4 on 2026-06-24 05:50

from django.db import migrations, models


def copy_group_fk_to_m2m(apps, schema_editor):
    StudentProfile = apps.get_model('portals', 'StudentProfile')
    StudyGroup = apps.get_model('portals', 'StudyGroup')

    for student in StudentProfile.objects.exclude(group_id__isnull=True).iterator():
        group = StudyGroup.objects.filter(pk=student.group_id).first()
        if group is not None:
            group.students.add(student)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0001_initial_portal_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='students',
            field=models.ManyToManyField(
                blank=True,
                help_text='Students in this group. One student may belong to several groups.',
                related_name='groups',
                to='portals.studentprofile',
                verbose_name='Students',
            ),
        ),
        migrations.RunPython(copy_group_fk_to_m2m, noop_reverse),
        migrations.RemoveField(
            model_name='studentprofile',
            name='group',
        ),
    ]
