# Generated by Django 6.0.4 on 2026-06-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0002_student_group_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='portals/profiles/students/', verbose_name='Profile photo'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='portals/profiles/teachers/', verbose_name='Profile photo'),
        ),
    ]
