# Generated by Django 6.0.4 on 2026-06-24 06:48

import portals.utils.normalize_phone_number
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0003_profile_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30, validators=[portals.utils.normalize_phone_number.phone_number_validator], verbose_name='Phone'),
        ),
    ]
