# Generated by Django 5.2.15 on 2026-06-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0006_teacher_course_specializations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachercoursespecialization',
            name='course_type',
            field=models.CharField(choices=[('general_english', 'General English'), ('speaking', 'Speaking'), ('ielts', 'IELTS'), ('gmat', 'GMAT'), ('gre', 'GRE'), ('sat', 'SAT'), ('yos', 'YÖS'), ('ales', 'ALES'), ('study_abroad', 'Study abroad'), ('other', 'Other')], max_length=32, verbose_name='Course type'),
        ),
    ]
