# Generated by Django 5.2.15 on 2026-06-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0013_quiz_question_prompt_and_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentprofile',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='parent_profiles', to='portals.studentprofile', verbose_name='Linked students'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='media_url',
            field=models.URLField(blank=True, help_text='Optional external link (e.g. YouTube) instead of an uploaded file.', verbose_name='Media URL'),
        ),
    ]
