# Generated by Django 5.2.15 on 2026-06-25 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0016_quiz_student_service_m2m'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('-lesson_date', '-created_at', 'id'), 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
    ]
