# Generated by Django 5.2.15 on 2026-06-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0023_quiz_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='duration_sec',
            field=models.PositiveIntegerField(default=0, verbose_name='Duration (seconds)'),
        ),
    ]
