# Generated by Django 5.2.15 on 2026-06-25 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0027_portal_notification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='portalnotification',
            new_name='portals_por_teacher_d75e4c_idx',
            old_name='portals_not_teacher_8b0f0d_idx',
        ),
        migrations.RenameIndex(
            model_name='portalnotification',
            new_name='portals_por_parent__414e2e_idx',
            old_name='portals_not_parent_4a8c2e_idx',
        ),
    ]
