# Generated by Django 5.2.15 on 2026-06-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0029_quiz_result_review_notification_kinds'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='portalnotification',
            new_name='portals_por_student_941cad_idx',
            old_name='portals_not_student_6d2a1b_idx',
        ),
    ]
