# Generated by Django 5.2.15 on 2026-06-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0037_studygroup_courses_remove_level'),
        ('projects', '0017_sale_remove_apply_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='courses',
            field=models.ManyToManyField(blank=True, help_text='Site courses linked to this group.', related_name='study_groups', to='projects.service', verbose_name='Courses'),
        ),
    ]
