# Generated by Django 5.2.15 on 2026-06-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0039_lesson_category_remove_lesson_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncategory',
            name='service',
            field=models.CharField(choices=[('general_english', 'General English'), ('speaking', 'Speaking'), ('ielts', 'IELTS'), ('gmat', 'GMAT'), ('gre', 'GRE'), ('sat', 'SAT'), ('yos', 'YÖS'), ('ales', 'ALES'), ('study_abroad', 'Study abroad'), ('other', 'Other')], db_index=True, max_length=32, verbose_name='Service'),
        ),
    ]
