# Generated by Django 5.2.15 on 2026-06-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0042_remove_coursetype_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='total_score',
            field=models.FloatField(blank=True, help_text='Manual-review quizzes: score from 0 to 10. Variant quizzes: auto-calculated.', null=True, verbose_name='Total score'),
        ),
    ]
