# Generated by Django 6.0.4 on 2026-07-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0047_listening_audio_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='parent',
        ),
        migrations.AddField(
            model_name='listeningaudio',
            name='is_time_limited',
            field=models.BooleanField(default=False, help_text='When enabled, set a time limit in minutes for the student attempt.', verbose_name='Time limited'),
        ),
        migrations.AddField(
            model_name='listeningaudio',
            name='requires_manual_review',
            field=models.BooleanField(default=True, help_text='Teacher reviews the submission and writes feedback.', verbose_name='Manual review'),
        ),
        migrations.AddField(
            model_name='listeningaudio',
            name='time_limit_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Required when time limited is enabled.', null=True, verbose_name='Time limit (minutes)'),
        ),
    ]
