# Generated by Django 5.2.15 on 2026-07-02 10:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0053_quizresult_completion_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningquestion',
            name='question',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Written prompt for the student. Leave blank for a numbered answer line only, or add answer options below for a multiple-choice task.', verbose_name='Question'),
        ),
    ]
