# Generated by Django 5.2.15 on 2026-07-02 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0055_listeningaudioplay'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='listeningaudioplay',
            new_name='portals_lis_student_cfba39_idx',
            old_name='portals_lis_student_6f0f0d_idx',
        ),
    ]
