# Generated by Django 6.0.4 on 2026-07-02 14:59

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0057_delete_listeningaudioplay'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('title', models.CharField(blank=True, help_text='Short label, e.g. Passage 1.', max_length=255, verbose_name='Title')),
                ('instructions', ckeditor.fields.RichTextField(blank=True, help_text='Task instructions shown above the passage.', verbose_name='Instructions')),
                ('body', ckeditor.fields.RichTextField(help_text='The reading passage shown to the student.', verbose_name='Passage text')),
            ],
            options={
                'verbose_name': 'Reading passage',
                'verbose_name_plural': 'Reading passages',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ReadingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple choice'), ('tfng', 'True / False / Not Given'), ('ynng', 'Yes / No / Not Given'), ('sentence_completion', 'Sentence completion'), ('summary_completion', 'Summary completion'), ('note_completion', 'Note completion'), ('table_completion', 'Table completion'), ('flowchart_completion', 'Flow-chart completion'), ('diagram_label', 'Diagram label completion'), ('short_answer', 'Short answer'), ('matching_headings', 'Matching headings'), ('matching_info', 'Matching information'), ('matching_features', 'Matching features'), ('matching_sentence_endings', 'Matching sentence endings')], default='mcq', max_length=32, verbose_name='Question type')),
                ('question', ckeditor.fields.RichTextField(blank=True, help_text='Prompt, table, flow-chart, or diagram context. Leave blank for a numbered answer line only when appropriate.', verbose_name='Question')),
                ('answer_options', models.JSONField(blank=True, default=list, help_text='Required for multiple choice. Leave empty for fixed or group options.', verbose_name='Answer options')),
                ('correct_option_index', models.PositiveIntegerField(default=0, verbose_name='Correct option index')),
                ('correct_answer', models.CharField(blank=True, help_text='Exact text for gap-fill tasks or the matching option label.', max_length=500, verbose_name='Correct answer')),
                ('question_config', models.JSONField(blank=True, default=dict, help_text='Word limits, alternatives, paragraph refs, etc.', verbose_name='Question config')),
            ],
            options={
                'verbose_name': 'Reading question',
                'verbose_name_plural': 'Reading questions',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ReadingQuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('instructions', ckeditor.fields.RichTextField(blank=True, verbose_name='Instructions')),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple choice'), ('tfng', 'True / False / Not Given'), ('ynng', 'Yes / No / Not Given'), ('sentence_completion', 'Sentence completion'), ('summary_completion', 'Summary completion'), ('note_completion', 'Note completion'), ('table_completion', 'Table completion'), ('flowchart_completion', 'Flow-chart completion'), ('diagram_label', 'Diagram label completion'), ('short_answer', 'Short answer'), ('matching_headings', 'Matching headings'), ('matching_info', 'Matching information'), ('matching_features', 'Matching features'), ('matching_sentence_endings', 'Matching sentence endings')], max_length=32, verbose_name='Question type')),
                ('option_pool', models.JSONField(blank=True, default=list, help_text='Shared choices for matching tasks, e.g. headings or endings.', verbose_name='Option pool')),
            ],
            options={
                'verbose_name': 'Reading question group',
                'verbose_name_plural': 'Reading question groups',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='quiz',
            name='portals_quiz_manual_mode_at_most_one',
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_reading',
            field=models.BooleanField(default=False, help_text='IELTS-style reading with passages and auto-scored answers. Only one quiz format can be active.', verbose_name='Reading (auto-scored)'),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_listening', False), ('is_essay', False), _connector='OR'), models.Q(('is_listening', False), ('is_speaking', False), _connector='OR'), models.Q(('is_listening', False), ('is_reading', False), _connector='OR'), models.Q(('is_essay', False), ('is_speaking', False), _connector='OR'), models.Q(('is_essay', False), ('is_reading', False), _connector='OR'), models.Q(('is_speaking', False), ('is_reading', False), _connector='OR')), name='portals_quiz_format_at_most_one'),
        ),
        migrations.AddField(
            model_name='readingpassage',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_passages', to='portals.quiz', verbose_name='Quiz'),
        ),
        migrations.AddField(
            model_name='readingquestion',
            name='passage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='portals.readingpassage', verbose_name='Passage'),
        ),
        migrations.AddField(
            model_name='readingquestiongroup',
            name='passage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_groups', to='portals.readingpassage', verbose_name='Passage'),
        ),
        migrations.AddField(
            model_name='readingquestion',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Optional shared option pool for matching tasks.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='portals.readingquestiongroup', verbose_name='Question group'),
        ),
    ]
