# Generated by Django 6.0.4 on 2026-07-04 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0063_speaking_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='IeltsMockTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], db_index=True, default='in_progress', max_length=16, verbose_name='Status')),
                ('current_section', models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing'), ('speaking', 'Speaking')], default='listening', max_length=16, verbose_name='Current section')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
            ],
            options={
                'verbose_name': 'IELTS mock test attempt',
                'verbose_name_plural': 'IELTS mock test attempts',
                'ordering': ('-started_at', '-id'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='portalnotification',
            name='portals_notification_teacher_result_kind_unique',
        ),
        migrations.RemoveConstraint(
            model_name='portalnotification',
            name='portals_notification_parent_result_unique',
        ),
        migrations.RemoveConstraint(
            model_name='portalnotification',
            name='portals_notification_student_result_unique',
        ),
        migrations.AlterField(
            model_name='portalnotification',
            name='kind',
            field=models.CharField(choices=[('submission_pending', 'Submission awaiting review'), ('result_published', 'Result published'), ('mock_test_completed', 'IELTS mock test completed')], default='result_published', max_length=32, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='portalnotification',
            name='quiz_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='portals.quizresult', verbose_name='Quiz result'),
        ),
        migrations.AddField(
            model_name='ieltsmocktestattempt',
            name='listening_quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mock_listening_attempts', to='portals.quiz', verbose_name='Listening quiz'),
        ),
        migrations.AddField(
            model_name='ieltsmocktestattempt',
            name='listening_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_listening_for', to='portals.quizresult', verbose_name='Listening result'),
        ),
        migrations.AddField(
            model_name='ieltsmocktestattempt',
            name='reading_quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mock_reading_attempts', to='portals.quiz', verbose_name='Reading quiz'),
        ),
        migrations.AddField(
            model_name='ieltsmocktestattempt',
            name='reading_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_reading_for', to='portals.quizresult', verbose_name='Reading result'),
        ),
        migrations.AddField(
            model_name='ieltsmocktestattempt',
            name='speaking_quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mock_speaking_attempts', to='portals.quiz', verbose_name='Speaking quiz'),
        ),
        migrations.AddField(
            model_name='ieltsmocktestattempt',
            name='speaking_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_speaking_for', to='portals.quizresult', verbose_name='Speaking result'),
        ),
        migrations.AddField(
            model_name='ieltsmocktestattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ielts_mock_attempts', to='portals.studentprofile', verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='ieltsmocktestattempt',
            name='writing_quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mock_writing_attempts', to='portals.quiz', verbose_name='Writing quiz'),
        ),
        migrations.AddField(
            model_name='ieltsmocktestattempt',
            name='writing_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mock_writing_for', to='portals.quizresult', verbose_name='Writing result'),
        ),
        migrations.AddField(
            model_name='portalnotification',
            name='ielts_mock_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='portals.ieltsmocktestattempt', verbose_name='IELTS mock test'),
        ),
        migrations.AddConstraint(
            model_name='portalnotification',
            constraint=models.CheckConstraint(condition=models.Q(('quiz_result__isnull', False), ('ielts_mock_test__isnull', False), _connector='OR'), name='portals_notification_has_target'),
        ),
        migrations.AddConstraint(
            model_name='portalnotification',
            constraint=models.UniqueConstraint(condition=models.Q(('quiz_result__isnull', False), ('teacher__isnull', False)), fields=('teacher', 'quiz_result', 'kind'), name='portals_notification_teacher_result_kind_unique'),
        ),
        migrations.AddConstraint(
            model_name='portalnotification',
            constraint=models.UniqueConstraint(condition=models.Q(('ielts_mock_test__isnull', False), ('teacher__isnull', False)), fields=('teacher', 'ielts_mock_test', 'kind'), name='portals_notification_teacher_mock_kind_unique'),
        ),
        migrations.AddConstraint(
            model_name='portalnotification',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False), ('quiz_result__isnull', False)), fields=('parent', 'quiz_result'), name='portals_notification_parent_result_unique'),
        ),
        migrations.AddConstraint(
            model_name='portalnotification',
            constraint=models.UniqueConstraint(condition=models.Q(('quiz_result__isnull', False), ('student__isnull', False)), fields=('student', 'quiz_result'), name='portals_notification_student_result_unique'),
        ),
        migrations.AddIndex(
            model_name='ieltsmocktestattempt',
            index=models.Index(fields=['student', 'status', '-started_at'], name='portals_iel_student_80f0d7_idx'),
        ),
    ]
