# Generated by Django 5.2.15 on 2026-07-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0065_lesson_attachment_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='is_essay',
            field=models.BooleanField(default=False, help_text='Written work — teacher grades and replies with corrections.', verbose_name='Writing (manual review)'),
        ),
    ]
