# Generated by Django 6.0.4 on 2026-07-06 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0069_quizresult_ielts_mock_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portalnotification',
            name='kind',
            field=models.CharField(choices=[('submission_pending', 'Submission awaiting review'), ('result_published', 'Result published'), ('mock_test_completed', 'IELTS mock test completed'), ('mock_test_section_review', 'IELTS mock test section review'), ('mock_test_results_published', 'IELTS mock test results published'), ('weekly_score_published', 'Weekly score published')], default='result_published', max_length=32, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='ielts_mock_attempt',
            field=models.ForeignKey(blank=True, help_text='Set when this result belongs to a mock test section (not a standalone quiz).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_results', to='portals.ieltsmocktestattempt', verbose_name='IELTS mock test attempt'),
        ),
    ]
