# Generated by Django 6.0.4 on 2026-07-06 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0070_quizresult_mock_attempt_set_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='is_listening',
            field=models.BooleanField(default=False, help_text='Multiple-choice listening quiz scored automatically when the student submits. No multiple-choice variants — only one manual mode can be active.', verbose_name='Listening (auto-scored)'),
        ),
        migrations.AlterField(
            model_name='quizresultreview',
            name='score',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='score',
            name='max_value',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Max value'),
        ),
        migrations.AlterField(
            model_name='score',
            name='value',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='weeklystudentscore',
            name='comment',
            field=models.TextField(blank=True, max_length=500, verbose_name='Comment'),
        ),
    ]
