# Generated by Django 6.0.4 on 2026-07-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0071_score_validators_and_weekly_comment_max'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('group', 'weekday', 'start_time', 'effective_from'), name='portals_schedule_unique_slot'),
        ),
    ]
