# Generated by Django 6.0.4 on 2026-07-09 13:28

import django.db.models.deletion
import portals.utils.normalize_phone_number
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0074_student_mock_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MockTestPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_az', models.CharField(max_length=120, verbose_name='Name (AZ)')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='Name (EN)')),
                ('name_ru', models.CharField(blank=True, max_length=120, verbose_name='Name (RU)')),
                ('credits', models.PositiveIntegerField(help_text='Number of mock tests granted after successful payment.', verbose_name='Mock credits')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price (AZN)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Mock test package',
                'verbose_name_plural': 'Mock test packages',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AlterField(
            model_name='ieltsmocktestattempt',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ielts_mock_attempts', to='portals.studentprofile', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to='portals.studentprofile', verbose_name='Student'),
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30, validators=[portals.utils.normalize_phone_number.phone_number_validator], verbose_name='Phone')),
                ('mock_credits', models.PositiveIntegerField(default=0, help_text='Each started mock test consumes one credit.', verbose_name='Mock test credits')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Customer profile',
                'verbose_name_plural': 'Customer profiles',
                'ordering': ('user__username', 'id'),
            },
        ),
        migrations.AddField(
            model_name='ieltsmocktestattempt',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ielts_mock_attempts', to='portals.customerprofile', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to='portals.customerprofile', verbose_name='Customer'),
        ),
        migrations.AddIndex(
            model_name='ieltsmocktestattempt',
            index=models.Index(fields=['customer', 'status', '-started_at'], name='portals_iel_custome_6bef47_idx'),
        ),
        migrations.AddConstraint(
            model_name='ieltsmocktestattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('customer__isnull', True), ('student__isnull', False)), models.Q(('customer__isnull', False), ('student__isnull', True)), _connector='OR'), name='portals_mock_attempt_student_xor_customer'),
        ),
        migrations.AddConstraint(
            model_name='quizresult',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('customer__isnull', True), ('student__isnull', False)), models.Q(('customer__isnull', False), ('student__isnull', True)), _connector='OR'), name='portals_quiz_result_student_xor_customer'),
        ),
    ]
