# Generated by Django 6.0.4 on 2026-07-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0075_customer_mock_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='mock_credits',
            field=models.PositiveIntegerField(default=1, help_text='Each started mock test consumes one credit.', verbose_name='Mock test credits'),
        ),
    ]
