# Generated by Django 6.0.4 on 2026-07-09 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0076_customer_mock_credits_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalnotification',
            name='customer',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='notifications',
                to='portals.customerprofile',
                verbose_name='Customer',
            ),
        ),
        migrations.RemoveConstraint(
            model_name='portalnotification',
            name='portals_notification_single_recipient',
        ),
        migrations.AddConstraint(
            model_name='portalnotification',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ('customer__isnull', True),
                        ('parent__isnull', True),
                        ('student__isnull', True),
                        ('teacher__isnull', False),
                    )
                    | models.Q(
                        ('customer__isnull', True),
                        ('parent__isnull', False),
                        ('student__isnull', True),
                        ('teacher__isnull', True),
                    )
                    | models.Q(
                        ('customer__isnull', True),
                        ('parent__isnull', True),
                        ('student__isnull', False),
                        ('teacher__isnull', True),
                    )
                    | models.Q(
                        ('customer__isnull', False),
                        ('parent__isnull', True),
                        ('student__isnull', True),
                        ('teacher__isnull', True),
                    )
                ),
                name='portals_notification_single_recipient',
            ),
        ),
        migrations.AddConstraint(
            model_name='portalnotification',
            constraint=models.UniqueConstraint(
                condition=models.Q(('customer__isnull', False), ('ielts_mock_test__isnull', False)),
                fields=('customer', 'ielts_mock_test'),
                name='portals_notification_customer_mock_unique',
            ),
        ),
        migrations.AddIndex(
            model_name='portalnotification',
            index=models.Index(fields=['customer', 'is_read', '-created_at'], name='portals_po_custome_idx'),
        ),
    ]
