# Generated by Django 6.0.4 on 2026-07-09 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0077_portal_notification_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='teacher',
            field=models.ForeignKey(
                blank=True,
                help_text="Teacher who reviews this customer's mock Writing and Speaking submissions.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='customers',
                to='portals.teacherprofile',
                verbose_name='Reviewing teacher',
            ),
        ),
    ]
