# Generated by Django 5.2.15 on 2026-07-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0078_customer_reviewing_teacher'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='portalnotification',
            name='portals_notification_single_recipient',
        ),
        migrations.RenameIndex(
            model_name='portalnotification',
            new_name='portals_por_custome_47de79_idx',
            old_name='portals_po_custome_idx',
        ),
        migrations.AddConstraint(
            model_name='portalnotification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('customer__isnull', True), ('parent__isnull', True), ('student__isnull', True), ('teacher__isnull', False)), models.Q(('customer__isnull', True), ('parent__isnull', False), ('student__isnull', True), ('teacher__isnull', True)), models.Q(('customer__isnull', True), ('parent__isnull', True), ('student__isnull', False), ('teacher__isnull', True)), models.Q(('customer__isnull', False), ('parent__isnull', True), ('student__isnull', True), ('teacher__isnull', True)), _connector='OR'), name='portals_notification_single_recipient'),
        ),
    ]
