# Generated by Django 6.0.4 on 2026-07-09 19:40

from django.db import migrations, models


def mark_existing_customer_attempts_credit_consumed(apps, schema_editor):
    IeltsMockTestAttempt = apps.get_model('portals', 'IeltsMockTestAttempt')
    IeltsMockTestAttempt.objects.filter(customer__isnull=False).update(credit_consumed=True)


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0079_remove_portalnotification_portals_notification_single_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ieltsmocktestattempt',
            name='credit_consumed',
            field=models.BooleanField(
                default=False,
                help_text='Customer mock credit is deducted when the first quiz section starts.',
                verbose_name='Credit consumed',
            ),
        ),
        migrations.RunPython(
            mark_existing_customer_attempts_credit_consumed,
            migrations.RunPython.noop,
        ),
    ]
