# Generated by Django 5.2.15 on 2026-07-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0080_ieltsmocktestattempt_credit_consumed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='mock_credits',
            field=models.PositiveIntegerField(default=1, help_text='Each started mock test section consumes one credit when you press Start quiz.', verbose_name='Mock test credits'),
        ),
    ]
