# Generated by Django 5.2.15 on 2026-07-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0081_alter_customerprofile_mock_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_ielts',
            field=models.BooleanField(
                default=False,
                help_text='Marks this quiz as part of the IELTS exam program.',
                verbose_name='IELTS',
            ),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_sat',
            field=models.BooleanField(
                default=False,
                help_text='Marks this quiz as part of the SAT exam program.',
                verbose_name='SAT',
            ),
        ),
    ]
