# Generated by Django 5.2.15 on 2026-07-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0084_delete_mocktestpackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='is_math',
            field=models.BooleanField(default=False, help_text='SAT Math section — auto-scored with passages/questions like Reading. Only available when SAT is enabled. Choose this yourself; it is not set automatically.', verbose_name='Math (auto-scored)'),
        ),
        migrations.AlterField(
            model_name='studentmockaccess',
            name='is_active',
            field=models.BooleanField(default=False, help_text='When enabled, the student can start a mock test.', verbose_name='Active'),
        ),
    ]
