# Generated by Django 6.0.4 on 2026-07-13 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0091_weekly_score_study_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('file', models.FileField(blank=True, null=True, upload_to='portals/lessons/homework/', verbose_name='File')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Original filename')),
                ('file_kind', models.CharField(blank=True, choices=[('pdf', 'PDF'), ('word', 'Word'), ('txt', 'Text')], max_length=16, verbose_name='File type')),
                ('submitted_at', models.DateTimeField(auto_now=True, verbose_name='Submitted at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='portals.lesson', verbose_name='Lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_homeworks', to='portals.studentprofile', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Lesson homework',
                'verbose_name_plural': 'Lesson homeworks',
                'ordering': ('-submitted_at', 'id'),
                'constraints': [models.UniqueConstraint(fields=('lesson', 'student'), name='portals_lesson_homework_lesson_student_uniq')],
            },
        ),
    ]
