# Generated by Django 5.2.15 on 2026-07-13 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0092_lesson_homework'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='portalnotification',
            name='portals_notification_has_target',
        ),
        migrations.AddField(
            model_name='portalnotification',
            name='lesson_homework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='portals.lessonhomework', verbose_name='Lesson homework'),
        ),
        migrations.AlterField(
            model_name='portalnotification',
            name='kind',
            field=models.CharField(choices=[('submission_pending', 'Submission awaiting review'), ('result_published', 'Result published'), ('mock_test_completed', 'IELTS mock test completed'), ('mock_test_section_review', 'IELTS mock test section review'), ('mock_test_results_published', 'IELTS mock test results published'), ('weekly_score_published', 'Weekly score published'), ('homework_submitted', 'Homework submitted')], default='result_published', max_length=32, verbose_name='Type'),
        ),
        migrations.AddConstraint(
            model_name='portalnotification',
            constraint=models.CheckConstraint(condition=models.Q(('quiz_result__isnull', False), ('ielts_mock_test__isnull', False), ('weekly_student_score__isnull', False), ('lesson_homework__isnull', False), _connector='OR'), name='portals_notification_has_target'),
        ),
        migrations.AddConstraint(
            model_name='portalnotification',
            constraint=models.UniqueConstraint(condition=models.Q(('lesson_homework__isnull', False), ('teacher__isnull', False)), fields=('teacher', 'lesson_homework', 'kind'), name='portals_notification_teacher_homework_kind_unique'),
        ),
    ]
