# Generated by Django 5.2.15 on 2026-07-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0094_quizcategory_services_m2m'),
        ('projects', '0029_alter_service_bullet_list_az_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizcategory',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='Site courses linked to this quiz category.', null=True, related_name='quiz_categories', to='projects.service', verbose_name='Services'),
        ),
    ]
