# Generated by Django 5.2.16 on 2026-07-31 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0097_reading_group_types_data_cleanup'),
        ('projects', '0029_alter_service_bullet_list_az_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('target_role', models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('all', 'All students and parents')], default='all', max_length=16, verbose_name='Target role')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Offer notification',
                'verbose_name_plural': 'Offer notifications',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='OfferNotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Sent')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent at')),
            ],
            options={
                'verbose_name': 'Offer notification delivery',
                'verbose_name_plural': 'Offer notification deliveries',
                'ordering': ('-sent_at', '-id'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='portalnotification',
            name='portals_notification_has_target',
        ),
        migrations.AlterField(
            model_name='portalnotification',
            name='kind',
            field=models.CharField(choices=[('submission_pending', 'Submission awaiting review'), ('result_published', 'Result published'), ('mock_test_completed', 'IELTS mock test completed'), ('mock_test_section_review', 'IELTS mock test section review'), ('mock_test_results_published', 'IELTS mock test results published'), ('weekly_score_published', 'Weekly score published'), ('homework_submitted', 'Homework submitted'), ('offer_notification', 'Offer notification')], default='result_published', max_length=32, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='offernotification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_offer_notifications', to='portals.teacherprofile', verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='offernotification',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='Leave empty to send to all services', related_name='offer_notifications', to='projects.service', verbose_name='Services'),
        ),
        migrations.AddField(
            model_name='portalnotification',
            name='offer_notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='portals.offernotification', verbose_name='Offer notification'),
        ),
        migrations.AddConstraint(
            model_name='portalnotification',
            constraint=models.CheckConstraint(condition=models.Q(('quiz_result__isnull', False), ('ielts_mock_test__isnull', False), ('weekly_student_score__isnull', False), ('lesson_homework__isnull', False), ('offer_notification__isnull', False), _connector='OR'), name='portals_notification_has_target'),
        ),
        migrations.AddConstraint(
            model_name='portalnotification',
            constraint=models.UniqueConstraint(condition=models.Q(('offer_notification__isnull', False), ('student__isnull', False)), fields=('student', 'offer_notification'), name='portals_notification_student_offer_unique'),
        ),
        migrations.AddConstraint(
            model_name='portalnotification',
            constraint=models.UniqueConstraint(condition=models.Q(('offer_notification__isnull', False), ('parent__isnull', False)), fields=('parent', 'offer_notification'), name='portals_notification_parent_offer_unique'),
        ),
        migrations.AddField(
            model_name='offernotificationdelivery',
            name='offer_notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='portals.offernotification', verbose_name='Offer notification'),
        ),
        migrations.AddField(
            model_name='offernotificationdelivery',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_notification_deliveries', to='portals.parentprofile', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='offernotificationdelivery',
            name='portal_notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_delivery', to='portals.portalnotification', verbose_name='Portal notification'),
        ),
        migrations.AddField(
            model_name='offernotificationdelivery',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_notification_deliveries', to='portals.studentprofile', verbose_name='Student'),
        ),
        migrations.AddConstraint(
            model_name='offernotificationdelivery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('parent__isnull', True), ('student__isnull', False)), models.Q(('parent__isnull', False), ('student__isnull', True)), _connector='OR'), name='portals_offer_notification_delivery_single_recipient'),
        ),
    ]
