# Generated by Django 5.2.16 on 2026-07-31 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0098_offernotification_offernotificationdelivery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offernotification',
            name='created_by',
        ),
    ]
