# Generated by Django 6.1 on 2026-08-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0099_remove_offernotification_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('spr', 'Student-Produced Response')], default='mcq', help_text='MCQ: Multiple choice with options. SPR: Student-Produced Response (typed answer).', max_length=10, verbose_name='Answer type'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='spr_correct_answers',
            field=models.JSONField(blank=True, help_text='List of correct answers for SPR questions (e.g., ["7/2", "3.5"])', null=True, verbose_name='SPR correct answers'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='spr_max_length',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Maximum character length for SPR answer (5 for positive, 6 for negative)', null=True, verbose_name='SPR max length'),
        ),
    ]
