# Generated by Django 5.2.16 on 2026-08-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0100_quizquestion_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='correct_answer',
            field=models.TextField(blank=True, verbose_name='Correct answer'),
        ),
    ]
