# Generated by Django 5.2.16 on 2026-08-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0101_alter_quizquestion_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='answer_key',
            field=models.TextField(blank=True, help_text='Rich text explanation of the correct answer (supports HTML, images, etc.)', verbose_name='Answer key'),
        ),
    ]
