# Generated by Django 5.2.16 on 2026-08-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0102_quizquestion_answer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='answer_options',
            field=models.TextField(blank=True, help_text='HTML or JSON list of answer choices shown to the student. Not used for manual-review quizzes.', verbose_name='Answer options'),
        ),
    ]
