# Generated by Django 5.2.16 on 2026-08-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0103_alter_quizquestion_answer_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='answer_key',
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='answer_options',
            field=models.JSONField(blank=True, default=list, help_text='List of answer choices shown to the student. Not used for manual-review quizzes.', verbose_name='Answer options'),
        ),
    ]
