# Generated by Django 5.2.17 on 2026-08-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0104_remove_quizquestion_answer_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='spr_correct_answers',
            field=models.JSONField(blank=True, help_text='One or more accepted answers for SPR questions (e.g. ["7/2", "3.5"] or ["y = -x + 19"]).', null=True, verbose_name='SPR correct answers'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='spr_max_length',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional character limit for the student input. Leave blank for equations or free-text answers.', null=True, verbose_name='SPR max length'),
        ),
    ]
