# Generated by Django 5.2.17 on 2026-08-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0106_quiz_shared_passage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizcategory',
            options={'ordering': ('order', 'name', 'id'), 'verbose_name': 'Quiz category', 'verbose_name_plural': 'Quiz categories'},
        ),
        migrations.AddField(
            model_name='quizcategory',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in the portal quiz category list.', verbose_name='Order'),
        ),
    ]
