# Generated by Django 5.2.10 on 2026-08-12 15:08

from django.db import migrations, models
from django.utils.html import strip_tags


def _plain(value):
    return strip_tags(str(value or '')).strip()


def forwards_backfill_spr_answers(apps, schema_editor):
    ListeningQuestion = apps.get_model('portals', 'ListeningQuestion')
    for question in ListeningQuestion.objects.all().iterator():
        options = [
            str(item).strip()
            for item in (question.answer_options or [])
            if str(item).strip()
        ]
        if len(options) >= 2:
            continue
        if question.spr_correct_answers:
            continue
        answers = []
        primary = _plain(question.correct_answer)
        if primary:
            answers.append(primary)
        config = question.question_config or {}
        for item in config.get('accept_alternatives') or []:
            text = _plain(item)
            if text and text not in answers:
                answers.append(text)
        if answers:
            question.spr_correct_answers = answers
            question.save(update_fields=['spr_correct_answers'])


def backwards_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0107_quizcategory_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningquestion',
            name='spr_correct_answers',
            field=models.JSONField(
                blank=True,
                help_text=(
                    'One or more accepted answers for typed (gap-fill) listening questions '
                    '(e.g. ["library", "the library"]). Leave empty for multiple-choice tasks.'
                ),
                null=True,
                verbose_name='SPR correct answers',
            ),
        ),
        migrations.AddField(
            model_name='listeningquestion',
            name='spr_max_length',
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text=(
                    'Optional character limit for the student input on typed answers. '
                    'Leave blank for free-text answers.'
                ),
                null=True,
                verbose_name='SPR max length',
            ),
        ),
        migrations.RunPython(forwards_backfill_spr_answers, backwards_noop),
    ]
