# Generated by Django 5.2.17 on 2026-09-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0114_studentprofile_attendance_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='lessons_per_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Expected number of lessons per month (e.g. 8 or 12).', null=True, verbose_name='Lessons per month'),
        ),
    ]
