# Generated by Django 5.2.11 on 2026-02-24 23:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_alter_appealvacancy_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_az', models.CharField(max_length=250, verbose_name='Service adı (AZ)')),
                ('title_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Service adı (EN)')),
                ('title_ru', models.CharField(blank=True, max_length=250, null=True, verbose_name='Service adı (RU)')),
                ('description_az', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Service haqqında (AZ)')),
                ('description_en', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Service haqqında (EN)')),
                ('description_ru', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(2000)], verbose_name='Service haqqında (RU)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Vakansiya aktivliyi')),
            ],
            options={
                'verbose_name': 'Servis',
                'verbose_name_plural': 'Serviceslər',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='media',
            name='is_service_page_background_image',
            field=models.BooleanField(default=False, verbose_name='Servis səhifəsi üçün arxa plan şəkli'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='name_az',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kateqoriya adı (AZ)'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kateqoriya adı (EN)'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kateqoriya adı (RU)'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='media',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='projects.service', verbose_name='Servislər'),
        ),
    ]
