# Generated by Django 5.2.11 on 2026-02-24 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_service_media_is_service_page_background_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_at'], 'verbose_name': 'Servis', 'verbose_name_plural': 'Servislər'},
        ),
    ]
