# Generated by Django 5.2.11 on 2026-02-25 00:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_alter_service_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_az',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(800)], verbose_name='Service haqqında (AZ)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(800)], verbose_name='Service haqqında (EN)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_ru',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(800)], verbose_name='Service haqqında (RU)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Servis aktivliyi'),
        ),
    ]
